version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /sdk-go
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /providers/cassandra
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /providers/inmemory
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /providers/kubernetes
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /providers/openapi
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /providers/redis
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /testing
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
