// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/host/v1/agent_gateway.proto

package gatewaypb

import (
	v1 "github.com/kubling-community/kubling-grpc/sdk-go/kubling/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Host table that an agent can observe locally.
type HostTable int32

const (
	HostTable_HOST_TABLE_UNSPECIFIED        HostTable = 0
	HostTable_HOST_TABLE_FACTS              HostTable = 1
	HostTable_HOST_TABLE_CPU_INFO           HostTable = 2
	HostTable_HOST_TABLE_CPU_TIMES          HostTable = 3
	HostTable_HOST_TABLE_MEMORY             HostTable = 4
	HostTable_HOST_TABLE_FILESYSTEMS        HostTable = 5
	HostTable_HOST_TABLE_NETWORK_INTERFACES HostTable = 6
	HostTable_HOST_TABLE_NETWORK_IO         HostTable = 7
	HostTable_HOST_TABLE_PROCESSES          HostTable = 8
)

// Enum value maps for HostTable.
var (
	HostTable_name = map[int32]string{
		0: "HOST_TABLE_UNSPECIFIED",
		1: "HOST_TABLE_FACTS",
		2: "HOST_TABLE_CPU_INFO",
		3: "HOST_TABLE_CPU_TIMES",
		4: "HOST_TABLE_MEMORY",
		5: "HOST_TABLE_FILESYSTEMS",
		6: "HOST_TABLE_NETWORK_INTERFACES",
		7: "HOST_TABLE_NETWORK_IO",
		8: "HOST_TABLE_PROCESSES",
	}
	HostTable_value = map[string]int32{
		"HOST_TABLE_UNSPECIFIED":        0,
		"HOST_TABLE_FACTS":              1,
		"HOST_TABLE_CPU_INFO":           2,
		"HOST_TABLE_CPU_TIMES":          3,
		"HOST_TABLE_MEMORY":             4,
		"HOST_TABLE_FILESYSTEMS":        5,
		"HOST_TABLE_NETWORK_INTERFACES": 6,
		"HOST_TABLE_NETWORK_IO":         7,
		"HOST_TABLE_PROCESSES":          8,
	}
)

func (x HostTable) Enum() *HostTable {
	p := new(HostTable)
	*p = x
	return p
}

func (x HostTable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostTable) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_host_v1_agent_gateway_proto_enumTypes[0].Descriptor()
}

func (HostTable) Type() protoreflect.EnumType {
	return &file_kubling_host_v1_agent_gateway_proto_enumTypes[0]
}

func (x HostTable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostTable.Descriptor instead.
func (HostTable) EnumDescriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{0}
}

// Terminal state of an agent scan.
type ScanStatus int32

const (
	ScanStatus_SCAN_STATUS_UNSPECIFIED ScanStatus = 0
	ScanStatus_SCAN_STATUS_SUCCEEDED   ScanStatus = 1
	ScanStatus_SCAN_STATUS_FAILED      ScanStatus = 2
	ScanStatus_SCAN_STATUS_CANCELLED   ScanStatus = 3
)

// Enum value maps for ScanStatus.
var (
	ScanStatus_name = map[int32]string{
		0: "SCAN_STATUS_UNSPECIFIED",
		1: "SCAN_STATUS_SUCCEEDED",
		2: "SCAN_STATUS_FAILED",
		3: "SCAN_STATUS_CANCELLED",
	}
	ScanStatus_value = map[string]int32{
		"SCAN_STATUS_UNSPECIFIED": 0,
		"SCAN_STATUS_SUCCEEDED":   1,
		"SCAN_STATUS_FAILED":      2,
		"SCAN_STATUS_CANCELLED":   3,
	}
)

func (x ScanStatus) Enum() *ScanStatus {
	p := new(ScanStatus)
	*p = x
	return p
}

func (x ScanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_host_v1_agent_gateway_proto_enumTypes[1].Descriptor()
}

func (ScanStatus) Type() protoreflect.EnumType {
	return &file_kubling_host_v1_agent_gateway_proto_enumTypes[1]
}

func (x ScanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanStatus.Descriptor instead.
func (ScanStatus) EnumDescriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{1}
}

// Reason that the provider no longer requires an in-flight scan.
type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED       CancelReason = 0
	CancelReason_CANCEL_REASON_CLIENT_CANCELLED  CancelReason = 1
	CancelReason_CANCEL_REASON_DEADLINE_EXCEEDED CancelReason = 2
	CancelReason_CANCEL_REASON_PROVIDER_SHUTDOWN CancelReason = 3
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_CLIENT_CANCELLED",
		2: "CANCEL_REASON_DEADLINE_EXCEEDED",
		3: "CANCEL_REASON_PROVIDER_SHUTDOWN",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED":       0,
		"CANCEL_REASON_CLIENT_CANCELLED":  1,
		"CANCEL_REASON_DEADLINE_EXCEEDED": 2,
		"CANCEL_REASON_PROVIDER_SHUTDOWN": 3,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_host_v1_agent_gateway_proto_enumTypes[2].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_kubling_host_v1_agent_gateway_proto_enumTypes[2]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{2}
}

// Message sent from a host agent to the Host Provider.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectRequest_Hello
	//	*ConnectRequest_Heartbeat
	//	*ConnectRequest_ScanBatch
	//	*ConnectRequest_ScanFinished
	Payload       isConnectRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetPayload() isConnectRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectRequest) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConnectRequest) GetScanBatch() *ScanBatch {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_ScanBatch); ok {
			return x.ScanBatch
		}
	}
	return nil
}

func (x *ConnectRequest) GetScanFinished() *ScanFinished {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_ScanFinished); ok {
			return x.ScanFinished
		}
	}
	return nil
}

type isConnectRequest_Payload interface {
	isConnectRequest_Payload()
}

type ConnectRequest_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ConnectRequest_ScanBatch struct {
	ScanBatch *ScanBatch `protobuf:"bytes,3,opt,name=scan_batch,json=scanBatch,proto3,oneof"`
}

type ConnectRequest_ScanFinished struct {
	ScanFinished *ScanFinished `protobuf:"bytes,4,opt,name=scan_finished,json=scanFinished,proto3,oneof"`
}

func (*ConnectRequest_Hello) isConnectRequest_Payload() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Payload() {}

func (*ConnectRequest_ScanBatch) isConnectRequest_Payload() {}

func (*ConnectRequest_ScanFinished) isConnectRequest_Payload() {}

// Message sent from the Host Provider to a connected host agent.
type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectResponse_SessionAccepted
	//	*ConnectResponse_HeartbeatAcknowledged
	//	*ConnectResponse_ScanRequest
	//	*ConnectResponse_CancelScan
	Payload       isConnectResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetPayload() isConnectResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectResponse) GetSessionAccepted() *SessionAccepted {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_SessionAccepted); ok {
			return x.SessionAccepted
		}
	}
	return nil
}

func (x *ConnectResponse) GetHeartbeatAcknowledged() *HeartbeatAcknowledged {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_HeartbeatAcknowledged); ok {
			return x.HeartbeatAcknowledged
		}
	}
	return nil
}

func (x *ConnectResponse) GetScanRequest() *ScanRequest {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_ScanRequest); ok {
			return x.ScanRequest
		}
	}
	return nil
}

func (x *ConnectResponse) GetCancelScan() *CancelScan {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_CancelScan); ok {
			return x.CancelScan
		}
	}
	return nil
}

type isConnectResponse_Payload interface {
	isConnectResponse_Payload()
}

type ConnectResponse_SessionAccepted struct {
	SessionAccepted *SessionAccepted `protobuf:"bytes,1,opt,name=session_accepted,json=sessionAccepted,proto3,oneof"`
}

type ConnectResponse_HeartbeatAcknowledged struct {
	HeartbeatAcknowledged *HeartbeatAcknowledged `protobuf:"bytes,2,opt,name=heartbeat_acknowledged,json=heartbeatAcknowledged,proto3,oneof"`
}

type ConnectResponse_ScanRequest struct {
	ScanRequest *ScanRequest `protobuf:"bytes,3,opt,name=scan_request,json=scanRequest,proto3,oneof"`
}

type ConnectResponse_CancelScan struct {
	CancelScan *CancelScan `protobuf:"bytes,4,opt,name=cancel_scan,json=cancelScan,proto3,oneof"`
}

func (*ConnectResponse_SessionAccepted) isConnectResponse_Payload() {}

func (*ConnectResponse_HeartbeatAcknowledged) isConnectResponse_Payload() {}

func (*ConnectResponse_ScanRequest) isConnectResponse_Payload() {}

func (*ConnectResponse_CancelScan) isConnectResponse_Payload() {}

// Version of the Agent Gateway protocol implemented by a peer.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// First and only handshake message sent by an agent on a new stream.
type AgentHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable random identifier generated and persisted by the agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Namespace requested by agent configuration. The provider must authorize
	// this value using transport credentials before accepting the session.
	RequestedNamespace string `protobuf:"bytes,2,opt,name=requested_namespace,json=requestedNamespace,proto3" json:"requested_namespace,omitempty"`
	// Mutable observed hostname. This is descriptive and never establishes
	// agent identity.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Informational build version of the host-agent binary.
	AgentVersion    string           `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion *ProtocolVersion `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Host table schema implemented by this agent.
	SchemaVersion string `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Maximum number of scans the agent permits concurrently. Zero is invalid.
	MaxConcurrentScans uint32 `protobuf:"varint,7,opt,name=max_concurrent_scans,json=maxConcurrentScans,proto3" json:"max_concurrent_scans,omitempty"`
	// Non-secret agent attributes available for inventory and policy.
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetRequestedNamespace() string {
	if x != nil {
		return x.RequestedNamespace
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *AgentHello) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AgentHello) GetMaxConcurrentScans() uint32 {
	if x != nil {
		return x.MaxConcurrentScans
	}
	return 0
}

func (x *AgentHello) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Successful session negotiation returned once by the provider.
type SessionAccepted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation        uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Namespace         string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	HostId            string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ProtocolVersion   *ProtocolVersion       `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion     string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,7,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	LeaseDuration     *durationpb.Duration   `protobuf:"bytes,8,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionAccepted) Reset() {
	*x = SessionAccepted{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccepted) ProtoMessage() {}

func (x *SessionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccepted.ProtoReflect.Descriptor instead.
func (*SessionAccepted) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SessionAccepted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAccepted) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionAccepted) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SessionAccepted) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *SessionAccepted) GetProtocolVersion() *ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *SessionAccepted) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SessionAccepted) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *SessionAccepted) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

// Renewable liveness signal sent while scans may be in flight.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-local monotonically increasing correlation number.
	Sequence      uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Confirms that the provider renewed the session lease.
type HeartbeatAcknowledged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sequence       uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatAcknowledged) Reset() {
	*x = HeartbeatAcknowledged{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAcknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAcknowledged) ProtoMessage() {}

func (x *HeartbeatAcknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAcknowledged.ProtoReflect.Descriptor instead.
func (*HeartbeatAcknowledged) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatAcknowledged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HeartbeatAcknowledged) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

// Typed local table scan dispatched to one agent session.
type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier unique among scans in the current session.
	ScanId string    `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Table  HostTable `protobuf:"varint,2,opt,name=table,proto3,enum=kubling.host.v1.HostTable" json:"table,omitempty"`
	// Ordered local columns expected in every returned ScanRow. Access fields
	// such as namespace and host_id are injected by the provider and never sent
	// to or accepted from an agent.
	Columns []string `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	// Absolute provider deadline. The agent must stop the scan after this time
	// even if a CancelScan message cannot be delivered.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Preferred maximum rows per batch. Zero leaves the choice to the agent.
	PreferredBatchRows uint32 `protobuf:"varint,5,opt,name=preferred_batch_rows,json=preferredBatchRows,proto3" json:"preferred_batch_rows,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanRequest) GetTable() HostTable {
	if x != nil {
		return x.Table
	}
	return HostTable_HOST_TABLE_UNSPECIFIED
}

func (x *ScanRequest) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ScanRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ScanRequest) GetPreferredBatchRows() uint32 {
	if x != nil {
		return x.PreferredBatchRows
	}
	return 0
}

// Ordered batch of rows produced by one scan.
type ScanBatch struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ScanId string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	// Contiguous zero-based index within this scan. It permits duplicate and
	// missing batches to be rejected without imposing ordering across agents.
	BatchIndex    uint64     `protobuf:"varint,2,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	Rows          []*ScanRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanBatch) Reset() {
	*x = ScanBatch{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBatch) ProtoMessage() {}

func (x *ScanBatch) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBatch.ProtoReflect.Descriptor instead.
func (*ScanBatch) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ScanBatch) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanBatch) GetBatchIndex() uint64 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *ScanBatch) GetRows() []*ScanRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Values ordered according to ScanRequest.columns.
type ScanRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*v1.Value            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRow) Reset() {
	*x = ScanRow{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRow) ProtoMessage() {}

func (x *ScanRow) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRow.ProtoReflect.Descriptor instead.
func (*ScanRow) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ScanRow) GetValues() []*v1.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Final and unique agent message for a scan.
type ScanFinished struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ScanId string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Status ScanStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=kubling.host.v1.ScanStatus" json:"status,omitempty"`
	// SUCCEEDED may include non-fatal warnings. FAILED must include at least one
	// diagnostic explaining the failure. The provider, rather than the agent,
	// decides whether a failed target produces a strict or partial query result.
	Diagnostics   []*ScanDiagnostic `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanFinished) Reset() {
	*x = ScanFinished{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFinished) ProtoMessage() {}

func (x *ScanFinished) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFinished.ProtoReflect.Descriptor instead.
func (*ScanFinished) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ScanFinished) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanFinished) GetStatus() ScanStatus {
	if x != nil {
		return x.Status
	}
	return ScanStatus_SCAN_STATUS_UNSPECIFIED
}

func (x *ScanFinished) GetDiagnostics() []*ScanDiagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Structured agent-side diagnostic safe to propagate to Kubling.
type ScanDiagnostic struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional local object identifier such as a mount point or process ID. It
	// must never contain credentials or endpoint URIs with embedded secrets.
	Target        string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Retryable     bool   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanDiagnostic) Reset() {
	*x = ScanDiagnostic{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDiagnostic) ProtoMessage() {}

func (x *ScanDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDiagnostic.ProtoReflect.Descriptor instead.
func (*ScanDiagnostic) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *ScanDiagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ScanDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScanDiagnostic) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ScanDiagnostic) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// Requests cooperative cancellation of a scan.
type CancelScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Reason        CancelReason           `protobuf:"varint,2,opt,name=reason,proto3,enum=kubling.host.v1.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScan) Reset() {
	*x = CancelScan{}
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScan) ProtoMessage() {}

func (x *CancelScan) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_host_v1_agent_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScan.ProtoReflect.Descriptor instead.
func (*CancelScan) Descriptor() ([]byte, []int) {
	return file_kubling_host_v1_agent_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CancelScan) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CancelScan) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

var File_kubling_host_v1_agent_gateway_proto protoreflect.FileDescriptor

const file_kubling_host_v1_agent_gateway_proto_rawDesc = "" +
	"\n" +
	"#kubling/host/v1/agent_gateway.proto\x12\x0fkubling.host.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16kubling/v1/value.proto\"\x8f\x02\n" +
	"\x0eConnectRequest\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.kubling.host.v1.AgentHelloH\x00R\x05hello\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.kubling.host.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\n" +
	"scan_batch\x18\x03 \x01(\v2\x1a.kubling.host.v1.ScanBatchH\x00R\tscanBatch\x12D\n" +
	"\rscan_finished\x18\x04 \x01(\v2\x1d.kubling.host.v1.ScanFinishedH\x00R\fscanFinishedB\t\n" +
	"\apayload\"\xcf\x02\n" +
	"\x0fConnectResponse\x12M\n" +
	"\x10session_accepted\x18\x01 \x01(\v2 .kubling.host.v1.SessionAcceptedH\x00R\x0fsessionAccepted\x12_\n" +
	"\x16heartbeat_acknowledged\x18\x02 \x01(\v2&.kubling.host.v1.HeartbeatAcknowledgedH\x00R\x15heartbeatAcknowledged\x12A\n" +
	"\fscan_request\x18\x03 \x01(\v2\x1c.kubling.host.v1.ScanRequestH\x00R\vscanRequest\x12>\n" +
	"\vcancel_scan\x18\x04 \x01(\v2\x1b.kubling.host.v1.CancelScanH\x00R\n" +
	"cancelScanB\t\n" +
	"\apayload\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\xcb\x03\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12/\n" +
	"\x13requested_namespace\x18\x02 \x01(\tR\x12requestedNamespace\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12K\n" +
	"\x10protocol_version\x18\x05 \x01(\v2 .kubling.host.v1.ProtocolVersionR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x120\n" +
	"\x14max_concurrent_scans\x18\a \x01(\rR\x12maxConcurrentScans\x12K\n" +
	"\n" +
	"attributes\x18\b \x03(\v2+.kubling.host.v1.AgentHello.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x03\n" +
	"\x0fSessionAccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12K\n" +
	"\x10protocol_version\x18\x05 \x01(\v2 .kubling.host.v1.ProtocolVersionR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x12H\n" +
	"\x12heartbeat_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12@\n" +
	"\x0elease_duration\x18\b \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\"'\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"y\n" +
	"\x15HeartbeatAcknowledged\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12D\n" +
	"\x10lease_expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"\xdc\x01\n" +
	"\vScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x120\n" +
	"\x05table\x18\x02 \x01(\x0e2\x1a.kubling.host.v1.HostTableR\x05table\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x120\n" +
	"\x14preferred_batch_rows\x18\x05 \x01(\rR\x12preferredBatchRows\"s\n" +
	"\tScanBatch\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x1f\n" +
	"\vbatch_index\x18\x02 \x01(\x04R\n" +
	"batchIndex\x12,\n" +
	"\x04rows\x18\x03 \x03(\v2\x18.kubling.host.v1.ScanRowR\x04rows\"4\n" +
	"\aScanRow\x12)\n" +
	"\x06values\x18\x01 \x03(\v2\x11.kubling.v1.ValueR\x06values\"\x9f\x01\n" +
	"\fScanFinished\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.kubling.host.v1.ScanStatusR\x06status\x12A\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x1f.kubling.host.v1.ScanDiagnosticR\vdiagnostics\"t\n" +
	"\x0eScanDiagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"\\\n" +
	"\n" +
	"CancelScan\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x125\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1d.kubling.host.v1.CancelReasonR\x06reason*\xfb\x01\n" +
	"\tHostTable\x12\x1a\n" +
	"\x16HOST_TABLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HOST_TABLE_FACTS\x10\x01\x12\x17\n" +
	"\x13HOST_TABLE_CPU_INFO\x10\x02\x12\x18\n" +
	"\x14HOST_TABLE_CPU_TIMES\x10\x03\x12\x15\n" +
	"\x11HOST_TABLE_MEMORY\x10\x04\x12\x1a\n" +
	"\x16HOST_TABLE_FILESYSTEMS\x10\x05\x12!\n" +
	"\x1dHOST_TABLE_NETWORK_INTERFACES\x10\x06\x12\x19\n" +
	"\x15HOST_TABLE_NETWORK_IO\x10\a\x12\x18\n" +
	"\x14HOST_TABLE_PROCESSES\x10\b*w\n" +
	"\n" +
	"ScanStatus\x12\x1b\n" +
	"\x17SCAN_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SCAN_STATUS_SUCCEEDED\x10\x01\x12\x16\n" +
	"\x12SCAN_STATUS_FAILED\x10\x02\x12\x19\n" +
	"\x15SCAN_STATUS_CANCELLED\x10\x03*\x9b\x01\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCANCEL_REASON_CLIENT_CANCELLED\x10\x01\x12#\n" +
	"\x1fCANCEL_REASON_DEADLINE_EXCEEDED\x10\x02\x12#\n" +
	"\x1fCANCEL_REASON_PROVIDER_SHUTDOWN\x10\x032g\n" +
	"\x13AgentGatewayService\x12P\n" +
	"\aConnect\x12\x1f.kubling.host.v1.ConnectRequest\x1a .kubling.host.v1.ConnectResponse(\x010\x01B\\ZZgithub.com/kubling-community/kubling-providers/providers/host/internal/gatewaypb;gatewaypbb\x06proto3"

var (
	file_kubling_host_v1_agent_gateway_proto_rawDescOnce sync.Once
	file_kubling_host_v1_agent_gateway_proto_rawDescData []byte
)

func file_kubling_host_v1_agent_gateway_proto_rawDescGZIP() []byte {
	file_kubling_host_v1_agent_gateway_proto_rawDescOnce.Do(func() {
		file_kubling_host_v1_agent_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_host_v1_agent_gateway_proto_rawDesc), len(file_kubling_host_v1_agent_gateway_proto_rawDesc)))
	})
	return file_kubling_host_v1_agent_gateway_proto_rawDescData
}

var file_kubling_host_v1_agent_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_kubling_host_v1_agent_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kubling_host_v1_agent_gateway_proto_goTypes = []any{
	(HostTable)(0),                // 0: kubling.host.v1.HostTable
	(ScanStatus)(0),               // 1: kubling.host.v1.ScanStatus
	(CancelReason)(0),             // 2: kubling.host.v1.CancelReason
	(*ConnectRequest)(nil),        // 3: kubling.host.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 4: kubling.host.v1.ConnectResponse
	(*ProtocolVersion)(nil),       // 5: kubling.host.v1.ProtocolVersion
	(*AgentHello)(nil),            // 6: kubling.host.v1.AgentHello
	(*SessionAccepted)(nil),       // 7: kubling.host.v1.SessionAccepted
	(*Heartbeat)(nil),             // 8: kubling.host.v1.Heartbeat
	(*HeartbeatAcknowledged)(nil), // 9: kubling.host.v1.HeartbeatAcknowledged
	(*ScanRequest)(nil),           // 10: kubling.host.v1.ScanRequest
	(*ScanBatch)(nil),             // 11: kubling.host.v1.ScanBatch
	(*ScanRow)(nil),               // 12: kubling.host.v1.ScanRow
	(*ScanFinished)(nil),          // 13: kubling.host.v1.ScanFinished
	(*ScanDiagnostic)(nil),        // 14: kubling.host.v1.ScanDiagnostic
	(*CancelScan)(nil),            // 15: kubling.host.v1.CancelScan
	nil,                           // 16: kubling.host.v1.AgentHello.AttributesEntry
	(*durationpb.Duration)(nil),   // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*v1.Value)(nil),              // 19: kubling.v1.Value
}
var file_kubling_host_v1_agent_gateway_proto_depIdxs = []int32{
	6,  // 0: kubling.host.v1.ConnectRequest.hello:type_name -> kubling.host.v1.AgentHello
	8,  // 1: kubling.host.v1.ConnectRequest.heartbeat:type_name -> kubling.host.v1.Heartbeat
	11, // 2: kubling.host.v1.ConnectRequest.scan_batch:type_name -> kubling.host.v1.ScanBatch
	13, // 3: kubling.host.v1.ConnectRequest.scan_finished:type_name -> kubling.host.v1.ScanFinished
	7,  // 4: kubling.host.v1.ConnectResponse.session_accepted:type_name -> kubling.host.v1.SessionAccepted
	9,  // 5: kubling.host.v1.ConnectResponse.heartbeat_acknowledged:type_name -> kubling.host.v1.HeartbeatAcknowledged
	10, // 6: kubling.host.v1.ConnectResponse.scan_request:type_name -> kubling.host.v1.ScanRequest
	15, // 7: kubling.host.v1.ConnectResponse.cancel_scan:type_name -> kubling.host.v1.CancelScan
	5,  // 8: kubling.host.v1.AgentHello.protocol_version:type_name -> kubling.host.v1.ProtocolVersion
	16, // 9: kubling.host.v1.AgentHello.attributes:type_name -> kubling.host.v1.AgentHello.AttributesEntry
	5,  // 10: kubling.host.v1.SessionAccepted.protocol_version:type_name -> kubling.host.v1.ProtocolVersion
	17, // 11: kubling.host.v1.SessionAccepted.heartbeat_interval:type_name -> google.protobuf.Duration
	17, // 12: kubling.host.v1.SessionAccepted.lease_duration:type_name -> google.protobuf.Duration
	18, // 13: kubling.host.v1.HeartbeatAcknowledged.lease_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 14: kubling.host.v1.ScanRequest.table:type_name -> kubling.host.v1.HostTable
	18, // 15: kubling.host.v1.ScanRequest.deadline:type_name -> google.protobuf.Timestamp
	12, // 16: kubling.host.v1.ScanBatch.rows:type_name -> kubling.host.v1.ScanRow
	19, // 17: kubling.host.v1.ScanRow.values:type_name -> kubling.v1.Value
	1,  // 18: kubling.host.v1.ScanFinished.status:type_name -> kubling.host.v1.ScanStatus
	14, // 19: kubling.host.v1.ScanFinished.diagnostics:type_name -> kubling.host.v1.ScanDiagnostic
	2,  // 20: kubling.host.v1.CancelScan.reason:type_name -> kubling.host.v1.CancelReason
	3,  // 21: kubling.host.v1.AgentGatewayService.Connect:input_type -> kubling.host.v1.ConnectRequest
	4,  // 22: kubling.host.v1.AgentGatewayService.Connect:output_type -> kubling.host.v1.ConnectResponse
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_kubling_host_v1_agent_gateway_proto_init() }
func file_kubling_host_v1_agent_gateway_proto_init() {
	if File_kubling_host_v1_agent_gateway_proto != nil {
		return
	}
	file_kubling_host_v1_agent_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectRequest_Hello)(nil),
		(*ConnectRequest_Heartbeat)(nil),
		(*ConnectRequest_ScanBatch)(nil),
		(*ConnectRequest_ScanFinished)(nil),
	}
	file_kubling_host_v1_agent_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*ConnectResponse_SessionAccepted)(nil),
		(*ConnectResponse_HeartbeatAcknowledged)(nil),
		(*ConnectResponse_ScanRequest)(nil),
		(*ConnectResponse_CancelScan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_host_v1_agent_gateway_proto_rawDesc), len(file_kubling_host_v1_agent_gateway_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubling_host_v1_agent_gateway_proto_goTypes,
		DependencyIndexes: file_kubling_host_v1_agent_gateway_proto_depIdxs,
		EnumInfos:         file_kubling_host_v1_agent_gateway_proto_enumTypes,
		MessageInfos:      file_kubling_host_v1_agent_gateway_proto_msgTypes,
	}.Build()
	File_kubling_host_v1_agent_gateway_proto = out.File
	file_kubling_host_v1_agent_gateway_proto_goTypes = nil
	file_kubling_host_v1_agent_gateway_proto_depIdxs = nil
}
