// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kubling/host/v1/agent_gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGatewayService_Connect_FullMethodName = "/kubling.host.v1.AgentGatewayService/Connect"
)

// AgentGatewayServiceClient is the client API for AgentGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentGatewayService connects host agents to one Host Provider.
//
// Authentication is carried by gRPC transport credentials and metadata, not
// by messages in this protocol. The first ConnectRequest must contain exactly
// one AgentHello. The provider accepts the session with SessionAccepted or
// terminates the stream with a gRPC status.
type AgentGatewayServiceClient interface {
	// Connect maintains one agent-initiated, bidirectional session.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error)
}

type agentGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayServiceClient(cc grpc.ClientConnInterface) AgentGatewayServiceClient {
	return &agentGatewayServiceClient{cc}
}

func (c *agentGatewayServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGatewayService_ServiceDesc.Streams[0], AgentGatewayService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGatewayService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectResponse]

// AgentGatewayServiceServer is the server API for AgentGatewayService service.
// All implementations must embed UnimplementedAgentGatewayServiceServer
// for forward compatibility.
//
// AgentGatewayService connects host agents to one Host Provider.
//
// Authentication is carried by gRPC transport credentials and metadata, not
// by messages in this protocol. The first ConnectRequest must contain exactly
// one AgentHello. The provider accepts the session with SessionAccepted or
// terminates the stream with a gRPC status.
type AgentGatewayServiceServer interface {
	// Connect maintains one agent-initiated, bidirectional session.
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error
	mustEmbedUnimplementedAgentGatewayServiceServer()
}

// UnimplementedAgentGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServiceServer struct{}

func (UnimplementedAgentGatewayServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentGatewayServiceServer) mustEmbedUnimplementedAgentGatewayServiceServer() {}
func (UnimplementedAgentGatewayServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServiceServer will
// result in compilation errors.
type UnsafeAgentGatewayServiceServer interface {
	mustEmbedUnimplementedAgentGatewayServiceServer()
}

func RegisterAgentGatewayServiceServer(s grpc.ServiceRegistrar, srv AgentGatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGatewayService_ServiceDesc, srv)
}

func _AgentGatewayService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGatewayService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]

// AgentGatewayService_ServiceDesc is the grpc.ServiceDesc for AgentGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubling.host.v1.AgentGatewayService",
	HandlerType: (*AgentGatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentGatewayService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kubling/host/v1/agent_gateway.proto",
}
