kubeconfig: local/kubeconfig.local.yaml
namespace: k3s-local
namespaceColumn:
  enabled: true
  includeInStableKeys: true
requestTimeout: 30s
qps: 50
burst: 100
blankNamespaceStrategy: ALL

schema:
  fieldExpansionDepth: 4
  resources:
    "batch/v1/cronjobs":
      fieldExpansionDepth: 6
