// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/capabilities.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Natural ordering of null values used by the provider.
type DefaultNullOrder int32

const (
	DefaultNullOrder_DEFAULT_NULL_ORDER_UNSPECIFIED DefaultNullOrder = 0
	// Null is considered greater than every non-null value.
	DefaultNullOrder_DEFAULT_NULL_ORDER_HIGH DefaultNullOrder = 1
	// Null is considered less than every non-null value.
	DefaultNullOrder_DEFAULT_NULL_ORDER_LOW DefaultNullOrder = 2
	// Null values always appear first, regardless of sort direction.
	DefaultNullOrder_DEFAULT_NULL_ORDER_FIRST DefaultNullOrder = 3
	// Null values always appear last, regardless of sort direction.
	DefaultNullOrder_DEFAULT_NULL_ORDER_LAST DefaultNullOrder = 4
	// The provider's natural null ordering is unknown or not stable.
	DefaultNullOrder_DEFAULT_NULL_ORDER_UNKNOWN DefaultNullOrder = 5
)

// Enum value maps for DefaultNullOrder.
var (
	DefaultNullOrder_name = map[int32]string{
		0: "DEFAULT_NULL_ORDER_UNSPECIFIED",
		1: "DEFAULT_NULL_ORDER_HIGH",
		2: "DEFAULT_NULL_ORDER_LOW",
		3: "DEFAULT_NULL_ORDER_FIRST",
		4: "DEFAULT_NULL_ORDER_LAST",
		5: "DEFAULT_NULL_ORDER_UNKNOWN",
	}
	DefaultNullOrder_value = map[string]int32{
		"DEFAULT_NULL_ORDER_UNSPECIFIED": 0,
		"DEFAULT_NULL_ORDER_HIGH":        1,
		"DEFAULT_NULL_ORDER_LOW":         2,
		"DEFAULT_NULL_ORDER_FIRST":       3,
		"DEFAULT_NULL_ORDER_LAST":        4,
		"DEFAULT_NULL_ORDER_UNKNOWN":     5,
	}
)

func (x DefaultNullOrder) Enum() *DefaultNullOrder {
	p := new(DefaultNullOrder)
	*p = x
	return p
}

func (x DefaultNullOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultNullOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_capabilities_proto_enumTypes[0].Descriptor()
}

func (DefaultNullOrder) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_capabilities_proto_enumTypes[0]
}

func (x DefaultNullOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultNullOrder.Descriptor instead.
func (DefaultNullOrder) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

// Requests the capabilities exposed by this provider server.
//
// Capabilities are global to the provider server and do not depend on a logical
// connection.
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

// Requests the complete Kubling schema exposed by this provider server.
type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{1}
}

// Capabilities exposed by the provider server.
type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Transactions  *TransactionCapabilities `protobuf:"bytes,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Query         *QueryCapabilities       `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Mutations     *MutationCapabilities    `protobuf:"bytes,3,opt,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapabilitiesResponse) GetTransactions() *TransactionCapabilities {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetQuery() *QueryCapabilities {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetMutations() *MutationCapabilities {
	if x != nil {
		return x.Mutations
	}
	return nil
}

// Schema definition exposed by the provider server.
type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubling DDL defining the logical schema exposed by the provider.
	//
	// This may include foreign tables and other schema objects required to access
	// the data source through this provider.
	SchemaDdl string `protobuf:"bytes,1,opt,name=schema_ddl,json=schemaDdl,proto3" json:"schema_ddl,omitempty"`
	// Provider-neutral structured relational metadata.
	//
	// Providers should set either metadata or schema_ddl, but not both. Static
	// providers may prefer DDL while providers that discover source metadata at
	// runtime should prefer this structured representation.
	Metadata      *SchemaMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchemaResponse) GetSchemaDdl() string {
	if x != nil {
		return x.SchemaDdl
	}
	return ""
}

func (x *GetSchemaResponse) GetMetadata() *SchemaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Native transaction capabilities.
type TransactionCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider supports native local transactions.
	//
	// When false, Kubling may provide transactional behavior through its
	// internal soft transaction mechanism.
	Supported     bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCapabilities) Reset() {
	*x = TransactionCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCapabilities) ProtoMessage() {}

func (x *TransactionCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCapabilities.ProtoReflect.Descriptor instead.
func (*TransactionCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionCapabilities) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

// Query capabilities that affect planning or exact result semantics.
type QueryCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider requires every query to include a filter criterion.
	//
	// This is a structural source restriction used by the Kubling planner.
	RequiresCriteria bool `protobuf:"varint,1,opt,name=requires_criteria,json=requiresCriteria,proto3" json:"requires_criteria,omitempty"`
	// Ordering capabilities.
	Ordering *OrderingCapabilities `protobuf:"bytes,2,opt,name=ordering,proto3" json:"ordering,omitempty"`
	// Pagination capabilities.
	Pagination *PaginationCapabilities `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Logical Kubling functions that the provider can evaluate exactly.
	//
	// Native data source function names must not be exposed here. The provider
	// is responsible for translating each logical function to its native
	// equivalent.
	SupportedFunctions []string `protobuf:"bytes,4,rep,name=supported_functions,json=supportedFunctions,proto3" json:"supported_functions,omitempty"`
	// Expression operators that the provider can evaluate exactly.
	Expressions   *ExpressionCapabilities `protobuf:"bytes,5,opt,name=expressions,proto3" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCapabilities) Reset() {
	*x = QueryCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCapabilities) ProtoMessage() {}

func (x *QueryCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCapabilities.ProtoReflect.Descriptor instead.
func (*QueryCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{5}
}

func (x *QueryCapabilities) GetRequiresCriteria() bool {
	if x != nil {
		return x.RequiresCriteria
	}
	return false
}

func (x *QueryCapabilities) GetOrdering() *OrderingCapabilities {
	if x != nil {
		return x.Ordering
	}
	return nil
}

func (x *QueryCapabilities) GetPagination() *PaginationCapabilities {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryCapabilities) GetSupportedFunctions() []string {
	if x != nil {
		return x.SupportedFunctions
	}
	return nil
}

func (x *QueryCapabilities) GetExpressions() *ExpressionCapabilities {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// Expression operators supported by a provider.
//
// Context-dependent source restrictions may still require the provider to
// reject a specific expression for a particular entity.
type ExpressionCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comparison operators that can be evaluated exactly.
	ComparisonOperators []ComparisonOperator `protobuf:"varint,1,rep,packed,name=comparison_operators,json=comparisonOperators,proto3,enum=kubling.provider.v1.ComparisonOperator" json:"comparison_operators,omitempty"`
	// Logical operators that can be evaluated exactly.
	LogicalOperators []LogicalOperator `protobuf:"varint,2,rep,packed,name=logical_operators,json=logicalOperators,proto3,enum=kubling.provider.v1.LogicalOperator" json:"logical_operators,omitempty"`
	// Null predicates that can be evaluated exactly.
	NullPredicateOperators []NullPredicateOperator `protobuf:"varint,3,rep,packed,name=null_predicate_operators,json=nullPredicateOperators,proto3,enum=kubling.provider.v1.NullPredicateOperator" json:"null_predicate_operators,omitempty"`
	// Pattern operators that can be evaluated exactly.
	PatternOperators []PatternOperator `protobuf:"varint,4,rep,packed,name=pattern_operators,json=patternOperators,proto3,enum=kubling.provider.v1.PatternOperator" json:"pattern_operators,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpressionCapabilities) Reset() {
	*x = ExpressionCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionCapabilities) ProtoMessage() {}

func (x *ExpressionCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionCapabilities.ProtoReflect.Descriptor instead.
func (*ExpressionCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{6}
}

func (x *ExpressionCapabilities) GetComparisonOperators() []ComparisonOperator {
	if x != nil {
		return x.ComparisonOperators
	}
	return nil
}

func (x *ExpressionCapabilities) GetLogicalOperators() []LogicalOperator {
	if x != nil {
		return x.LogicalOperators
	}
	return nil
}

func (x *ExpressionCapabilities) GetNullPredicateOperators() []NullPredicateOperator {
	if x != nil {
		return x.NullPredicateOperators
	}
	return nil
}

func (x *ExpressionCapabilities) GetPatternOperators() []PatternOperator {
	if x != nil {
		return x.PatternOperators
	}
	return nil
}

// Ordering capabilities.
type OrderingCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider can apply the requested ordering exactly.
	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	// True when the provider can explicitly control whether null values appear
	// first or last.
	ExplicitNullOrdering bool `protobuf:"varint,2,opt,name=explicit_null_ordering,json=explicitNullOrdering,proto3" json:"explicit_null_ordering,omitempty"`
	// Natural null ordering used when explicit null ordering is unavailable.
	DefaultNullOrder DefaultNullOrder `protobuf:"varint,3,opt,name=default_null_order,json=defaultNullOrder,proto3,enum=kubling.provider.v1.DefaultNullOrder" json:"default_null_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderingCapabilities) Reset() {
	*x = OrderingCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderingCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderingCapabilities) ProtoMessage() {}

func (x *OrderingCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderingCapabilities.ProtoReflect.Descriptor instead.
func (*OrderingCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{7}
}

func (x *OrderingCapabilities) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *OrderingCapabilities) GetExplicitNullOrdering() bool {
	if x != nil {
		return x.ExplicitNullOrdering
	}
	return false
}

func (x *OrderingCapabilities) GetDefaultNullOrder() DefaultNullOrder {
	if x != nil {
		return x.DefaultNullOrder
	}
	return DefaultNullOrder_DEFAULT_NULL_ORDER_UNSPECIFIED
}

// Pagination capabilities.
type PaginationCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider can enforce the requested row limit exactly.
	Limit bool `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// True when the provider can enforce the requested row offset exactly.
	Offset        bool `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationCapabilities) Reset() {
	*x = PaginationCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationCapabilities) ProtoMessage() {}

func (x *PaginationCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationCapabilities.ProtoReflect.Descriptor instead.
func (*PaginationCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{8}
}

func (x *PaginationCapabilities) GetLimit() bool {
	if x != nil {
		return x.Limit
	}
	return false
}

func (x *PaginationCapabilities) GetOffset() bool {
	if x != nil {
		return x.Offset
	}
	return false
}

// Mutation operations supported by the provider.
type MutationCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider supports insert operations.
	Insert bool `protobuf:"varint,1,opt,name=insert,proto3" json:"insert,omitempty"`
	// True when the provider supports update operations.
	Update bool `protobuf:"varint,2,opt,name=update,proto3" json:"update,omitempty"`
	// True when the provider supports delete operations.
	Delete bool `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	// True when insert operations can return generated values.
	GeneratedValues bool `protobuf:"varint,4,opt,name=generated_values,json=generatedValues,proto3" json:"generated_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutationCapabilities) Reset() {
	*x = MutationCapabilities{}
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationCapabilities) ProtoMessage() {}

func (x *MutationCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_capabilities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationCapabilities.ProtoReflect.Descriptor instead.
func (*MutationCapabilities) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_capabilities_proto_rawDescGZIP(), []int{9}
}

func (x *MutationCapabilities) GetInsert() bool {
	if x != nil {
		return x.Insert
	}
	return false
}

func (x *MutationCapabilities) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

func (x *MutationCapabilities) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

func (x *MutationCapabilities) GetGeneratedValues() bool {
	if x != nil {
		return x.GeneratedValues
	}
	return false
}

var File_kubling_provider_v1_capabilities_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_capabilities_proto_rawDesc = "" +
	"\n" +
	"&kubling/provider/v1/capabilities.proto\x12\x13kubling.provider.v1\x1a$kubling/provider/v1/expression.proto\x1a\"kubling/provider/v1/metadata.proto\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\x12\n" +
	"\x10GetSchemaRequest\"\xf2\x01\n" +
	"\x17GetCapabilitiesResponse\x12P\n" +
	"\ftransactions\x18\x01 \x01(\v2,.kubling.provider.v1.TransactionCapabilitiesR\ftransactions\x12<\n" +
	"\x05query\x18\x02 \x01(\v2&.kubling.provider.v1.QueryCapabilitiesR\x05query\x12G\n" +
	"\tmutations\x18\x03 \x01(\v2).kubling.provider.v1.MutationCapabilitiesR\tmutations\"s\n" +
	"\x11GetSchemaResponse\x12\x1d\n" +
	"\n" +
	"schema_ddl\x18\x01 \x01(\tR\tschemaDdl\x12?\n" +
	"\bmetadata\x18\x02 \x01(\v2#.kubling.provider.v1.SchemaMetadataR\bmetadata\"7\n" +
	"\x17TransactionCapabilities\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\"\xd4\x02\n" +
	"\x11QueryCapabilities\x12+\n" +
	"\x11requires_criteria\x18\x01 \x01(\bR\x10requiresCriteria\x12E\n" +
	"\bordering\x18\x02 \x01(\v2).kubling.provider.v1.OrderingCapabilitiesR\bordering\x12K\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2+.kubling.provider.v1.PaginationCapabilitiesR\n" +
	"pagination\x12/\n" +
	"\x13supported_functions\x18\x04 \x03(\tR\x12supportedFunctions\x12M\n" +
	"\vexpressions\x18\x05 \x01(\v2+.kubling.provider.v1.ExpressionCapabilitiesR\vexpressions\"\x80\x03\n" +
	"\x16ExpressionCapabilities\x12Z\n" +
	"\x14comparison_operators\x18\x01 \x03(\x0e2'.kubling.provider.v1.ComparisonOperatorR\x13comparisonOperators\x12Q\n" +
	"\x11logical_operators\x18\x02 \x03(\x0e2$.kubling.provider.v1.LogicalOperatorR\x10logicalOperators\x12d\n" +
	"\x18null_predicate_operators\x18\x03 \x03(\x0e2*.kubling.provider.v1.NullPredicateOperatorR\x16nullPredicateOperators\x12Q\n" +
	"\x11pattern_operators\x18\x04 \x03(\x0e2$.kubling.provider.v1.PatternOperatorR\x10patternOperators\"\xbf\x01\n" +
	"\x14OrderingCapabilities\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x124\n" +
	"\x16explicit_null_ordering\x18\x02 \x01(\bR\x14explicitNullOrdering\x12S\n" +
	"\x12default_null_order\x18\x03 \x01(\x0e2%.kubling.provider.v1.DefaultNullOrderR\x10defaultNullOrder\"F\n" +
	"\x16PaginationCapabilities\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\bR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\bR\x06offset\"\x89\x01\n" +
	"\x14MutationCapabilities\x12\x16\n" +
	"\x06insert\x18\x01 \x01(\bR\x06insert\x12\x16\n" +
	"\x06update\x18\x02 \x01(\bR\x06update\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\bR\x06delete\x12)\n" +
	"\x10generated_values\x18\x04 \x01(\bR\x0fgeneratedValues*\xca\x01\n" +
	"\x10DefaultNullOrder\x12\"\n" +
	"\x1eDEFAULT_NULL_ORDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEFAULT_NULL_ORDER_HIGH\x10\x01\x12\x1a\n" +
	"\x16DEFAULT_NULL_ORDER_LOW\x10\x02\x12\x1c\n" +
	"\x18DEFAULT_NULL_ORDER_FIRST\x10\x03\x12\x1b\n" +
	"\x17DEFAULT_NULL_ORDER_LAST\x10\x04\x12\x1e\n" +
	"\x1aDEFAULT_NULL_ORDER_UNKNOWN\x10\x05B\x86\x01\n" +
	"\x19com.kubling.provider.grpcB\x11CapabilitiesProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_capabilities_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_capabilities_proto_rawDescData []byte
)

func file_kubling_provider_v1_capabilities_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_capabilities_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_capabilities_proto_rawDesc), len(file_kubling_provider_v1_capabilities_proto_rawDesc)))
	})
	return file_kubling_provider_v1_capabilities_proto_rawDescData
}

var file_kubling_provider_v1_capabilities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubling_provider_v1_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kubling_provider_v1_capabilities_proto_goTypes = []any{
	(DefaultNullOrder)(0),           // 0: kubling.provider.v1.DefaultNullOrder
	(*GetCapabilitiesRequest)(nil),  // 1: kubling.provider.v1.GetCapabilitiesRequest
	(*GetSchemaRequest)(nil),        // 2: kubling.provider.v1.GetSchemaRequest
	(*GetCapabilitiesResponse)(nil), // 3: kubling.provider.v1.GetCapabilitiesResponse
	(*GetSchemaResponse)(nil),       // 4: kubling.provider.v1.GetSchemaResponse
	(*TransactionCapabilities)(nil), // 5: kubling.provider.v1.TransactionCapabilities
	(*QueryCapabilities)(nil),       // 6: kubling.provider.v1.QueryCapabilities
	(*ExpressionCapabilities)(nil),  // 7: kubling.provider.v1.ExpressionCapabilities
	(*OrderingCapabilities)(nil),    // 8: kubling.provider.v1.OrderingCapabilities
	(*PaginationCapabilities)(nil),  // 9: kubling.provider.v1.PaginationCapabilities
	(*MutationCapabilities)(nil),    // 10: kubling.provider.v1.MutationCapabilities
	(*SchemaMetadata)(nil),          // 11: kubling.provider.v1.SchemaMetadata
	(ComparisonOperator)(0),         // 12: kubling.provider.v1.ComparisonOperator
	(LogicalOperator)(0),            // 13: kubling.provider.v1.LogicalOperator
	(NullPredicateOperator)(0),      // 14: kubling.provider.v1.NullPredicateOperator
	(PatternOperator)(0),            // 15: kubling.provider.v1.PatternOperator
}
var file_kubling_provider_v1_capabilities_proto_depIdxs = []int32{
	5,  // 0: kubling.provider.v1.GetCapabilitiesResponse.transactions:type_name -> kubling.provider.v1.TransactionCapabilities
	6,  // 1: kubling.provider.v1.GetCapabilitiesResponse.query:type_name -> kubling.provider.v1.QueryCapabilities
	10, // 2: kubling.provider.v1.GetCapabilitiesResponse.mutations:type_name -> kubling.provider.v1.MutationCapabilities
	11, // 3: kubling.provider.v1.GetSchemaResponse.metadata:type_name -> kubling.provider.v1.SchemaMetadata
	8,  // 4: kubling.provider.v1.QueryCapabilities.ordering:type_name -> kubling.provider.v1.OrderingCapabilities
	9,  // 5: kubling.provider.v1.QueryCapabilities.pagination:type_name -> kubling.provider.v1.PaginationCapabilities
	7,  // 6: kubling.provider.v1.QueryCapabilities.expressions:type_name -> kubling.provider.v1.ExpressionCapabilities
	12, // 7: kubling.provider.v1.ExpressionCapabilities.comparison_operators:type_name -> kubling.provider.v1.ComparisonOperator
	13, // 8: kubling.provider.v1.ExpressionCapabilities.logical_operators:type_name -> kubling.provider.v1.LogicalOperator
	14, // 9: kubling.provider.v1.ExpressionCapabilities.null_predicate_operators:type_name -> kubling.provider.v1.NullPredicateOperator
	15, // 10: kubling.provider.v1.ExpressionCapabilities.pattern_operators:type_name -> kubling.provider.v1.PatternOperator
	0,  // 11: kubling.provider.v1.OrderingCapabilities.default_null_order:type_name -> kubling.provider.v1.DefaultNullOrder
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_capabilities_proto_init() }
func file_kubling_provider_v1_capabilities_proto_init() {
	if File_kubling_provider_v1_capabilities_proto != nil {
		return
	}
	file_kubling_provider_v1_expression_proto_init()
	file_kubling_provider_v1_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_capabilities_proto_rawDesc), len(file_kubling_provider_v1_capabilities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_capabilities_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_capabilities_proto_depIdxs,
		EnumInfos:         file_kubling_provider_v1_capabilities_proto_enumTypes,
		MessageInfos:      file_kubling_provider_v1_capabilities_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_capabilities_proto = out.File
	file_kubling_provider_v1_capabilities_proto_goTypes = nil
	file_kubling_provider_v1_capabilities_proto_depIdxs = nil
}
