// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/connection.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Opens a logical connection to the complete data universe managed by the
// provider.
type OpenConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConnectionRequest) Reset() {
	*x = OpenConnectionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConnectionRequest) ProtoMessage() {}

func (x *OpenConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConnectionRequest.ProtoReflect.Descriptor instead.
func (*OpenConnectionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{0}
}

// Result of opening a logical provider connection.
type OpenConnectionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier assigned to the logical connection.
	//
	// The identifier must be included in all subsequent operations performed
	// through this connection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenConnectionResponse) Reset() {
	*x = OpenConnectionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConnectionResponse) ProtoMessage() {}

func (x *OpenConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConnectionResponse.ProtoReflect.Descriptor instead.
func (*OpenConnectionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *OpenConnectionResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Closes an existing logical provider connection.
type CloseConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionRequest) Reset() {
	*x = CloseConnectionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionRequest) ProtoMessage() {}

func (x *CloseConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionRequest.ProtoReflect.Descriptor instead.
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{2}
}

func (x *CloseConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Result of closing a logical provider connection.
type CloseConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionResponse) Reset() {
	*x = CloseConnectionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionResponse) ProtoMessage() {}

func (x *CloseConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionResponse.ProtoReflect.Descriptor instead.
func (*CloseConnectionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{3}
}

type BeginTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{4}
}

func (x *BeginTransactionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Result of starting a native transaction.
type BeginTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{5}
}

// Commits the active native transaction.
type CommitTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{6}
}

func (x *CommitTransactionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Result of committing the active native transaction.
type CommitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionResponse) Reset() {
	*x = CommitTransactionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionResponse) ProtoMessage() {}

func (x *CommitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionResponse.ProtoReflect.Descriptor instead.
func (*CommitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{7}
}

// Rolls back the active native transaction.
type RollbackTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionRequest) Reset() {
	*x = RollbackTransactionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionRequest) ProtoMessage() {}

func (x *RollbackTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionRequest.ProtoReflect.Descriptor instead.
func (*RollbackTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackTransactionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Result of rolling back the active native transaction.
type RollbackTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionResponse) Reset() {
	*x = RollbackTransactionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionResponse) ProtoMessage() {}

func (x *RollbackTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionResponse.ProtoReflect.Descriptor instead.
func (*RollbackTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{9}
}

// Checks whether a logical connection currently has an active native transaction.
type IsInTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId  string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInTransactionRequest) Reset() {
	*x = IsInTransactionRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInTransactionRequest) ProtoMessage() {}

func (x *IsInTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInTransactionRequest.ProtoReflect.Descriptor instead.
func (*IsInTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{10}
}

func (x *IsInTransactionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Current transactional state of the logical connection.
type IsInTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the connection has an active native transaction.
	Active        bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsInTransactionResponse) Reset() {
	*x = IsInTransactionResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsInTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsInTransactionResponse) ProtoMessage() {}

func (x *IsInTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsInTransactionResponse.ProtoReflect.Descriptor instead.
func (*IsInTransactionResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{11}
}

func (x *IsInTransactionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Requests the connection-agnostic health state of the provider server.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{12}
}

// Health state of the provider server.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the provider server is ready to serve requests.
	//
	// Kubling may include this result when computing the engine's aggregate
	// health, depending on the data source configuration.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Optional provider-defined diagnostic information.
	//
	// This field must not contain credentials or other sensitive information.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_connection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_connection_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kubling_provider_v1_connection_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_connection_proto_rawDesc = "" +
	"\n" +
	"$kubling/provider/v1/connection.proto\x12\x13kubling.provider.v1\"\x17\n" +
	"\x15OpenConnectionRequest\"=\n" +
	"\x16OpenConnectionResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"=\n" +
	"\x16CloseConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x19\n" +
	"\x17CloseConnectionResponse\">\n" +
	"\x17BeginTransactionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x1a\n" +
	"\x18BeginTransactionResponse\"?\n" +
	"\x18CommitTransactionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x1b\n" +
	"\x19CommitTransactionResponse\"A\n" +
	"\x1aRollbackTransactionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x1d\n" +
	"\x1bRollbackTransactionResponse\"=\n" +
	"\x16IsInTransactionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"1\n" +
	"\x17IsInTransactionResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x84\x01\n" +
	"\x19com.kubling.provider.grpcB\x0fConnectionProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_connection_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_connection_proto_rawDescData []byte
)

func file_kubling_provider_v1_connection_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_connection_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_connection_proto_rawDesc), len(file_kubling_provider_v1_connection_proto_rawDesc)))
	})
	return file_kubling_provider_v1_connection_proto_rawDescData
}

var file_kubling_provider_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kubling_provider_v1_connection_proto_goTypes = []any{
	(*OpenConnectionRequest)(nil),       // 0: kubling.provider.v1.OpenConnectionRequest
	(*OpenConnectionResponse)(nil),      // 1: kubling.provider.v1.OpenConnectionResponse
	(*CloseConnectionRequest)(nil),      // 2: kubling.provider.v1.CloseConnectionRequest
	(*CloseConnectionResponse)(nil),     // 3: kubling.provider.v1.CloseConnectionResponse
	(*BeginTransactionRequest)(nil),     // 4: kubling.provider.v1.BeginTransactionRequest
	(*BeginTransactionResponse)(nil),    // 5: kubling.provider.v1.BeginTransactionResponse
	(*CommitTransactionRequest)(nil),    // 6: kubling.provider.v1.CommitTransactionRequest
	(*CommitTransactionResponse)(nil),   // 7: kubling.provider.v1.CommitTransactionResponse
	(*RollbackTransactionRequest)(nil),  // 8: kubling.provider.v1.RollbackTransactionRequest
	(*RollbackTransactionResponse)(nil), // 9: kubling.provider.v1.RollbackTransactionResponse
	(*IsInTransactionRequest)(nil),      // 10: kubling.provider.v1.IsInTransactionRequest
	(*IsInTransactionResponse)(nil),     // 11: kubling.provider.v1.IsInTransactionResponse
	(*HealthRequest)(nil),               // 12: kubling.provider.v1.HealthRequest
	(*HealthResponse)(nil),              // 13: kubling.provider.v1.HealthResponse
}
var file_kubling_provider_v1_connection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_connection_proto_init() }
func file_kubling_provider_v1_connection_proto_init() {
	if File_kubling_provider_v1_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_connection_proto_rawDesc), len(file_kubling_provider_v1_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_connection_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_connection_proto_depIdxs,
		MessageInfos:      file_kubling_provider_v1_connection_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_connection_proto = out.File
	file_kubling_provider_v1_connection_proto_goTypes = nil
	file_kubling_provider_v1_connection_proto_depIdxs = nil
}
