// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/expression.proto

package providerv1

import (
	v1 "github.com/kubling-community/kubling-grpc/sdk-go/kubling/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operators supported by comparison expressions.
type ComparisonOperator int32

const (
	ComparisonOperator_COMPARISON_OPERATOR_UNSPECIFIED           ComparisonOperator = 0
	ComparisonOperator_COMPARISON_OPERATOR_EQUAL                 ComparisonOperator = 1
	ComparisonOperator_COMPARISON_OPERATOR_NOT_EQUAL             ComparisonOperator = 2
	ComparisonOperator_COMPARISON_OPERATOR_LESS_THAN             ComparisonOperator = 3
	ComparisonOperator_COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL    ComparisonOperator = 4
	ComparisonOperator_COMPARISON_OPERATOR_GREATER_THAN          ComparisonOperator = 5
	ComparisonOperator_COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL ComparisonOperator = 6
)

// Enum value maps for ComparisonOperator.
var (
	ComparisonOperator_name = map[int32]string{
		0: "COMPARISON_OPERATOR_UNSPECIFIED",
		1: "COMPARISON_OPERATOR_EQUAL",
		2: "COMPARISON_OPERATOR_NOT_EQUAL",
		3: "COMPARISON_OPERATOR_LESS_THAN",
		4: "COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL",
		5: "COMPARISON_OPERATOR_GREATER_THAN",
		6: "COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL",
	}
	ComparisonOperator_value = map[string]int32{
		"COMPARISON_OPERATOR_UNSPECIFIED":           0,
		"COMPARISON_OPERATOR_EQUAL":                 1,
		"COMPARISON_OPERATOR_NOT_EQUAL":             2,
		"COMPARISON_OPERATOR_LESS_THAN":             3,
		"COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL":    4,
		"COMPARISON_OPERATOR_GREATER_THAN":          5,
		"COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL": 6,
	}
)

func (x ComparisonOperator) Enum() *ComparisonOperator {
	p := new(ComparisonOperator)
	*p = x
	return p
}

func (x ComparisonOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_expression_proto_enumTypes[0].Descriptor()
}

func (ComparisonOperator) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_expression_proto_enumTypes[0]
}

func (x ComparisonOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonOperator.Descriptor instead.
func (ComparisonOperator) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{0}
}

// Operators supported by logical expressions.
type LogicalOperator int32

const (
	LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED LogicalOperator = 0
	LogicalOperator_LOGICAL_OPERATOR_AND         LogicalOperator = 1
	LogicalOperator_LOGICAL_OPERATOR_OR          LogicalOperator = 2
	LogicalOperator_LOGICAL_OPERATOR_NOT         LogicalOperator = 3
)

// Enum value maps for LogicalOperator.
var (
	LogicalOperator_name = map[int32]string{
		0: "LOGICAL_OPERATOR_UNSPECIFIED",
		1: "LOGICAL_OPERATOR_AND",
		2: "LOGICAL_OPERATOR_OR",
		3: "LOGICAL_OPERATOR_NOT",
	}
	LogicalOperator_value = map[string]int32{
		"LOGICAL_OPERATOR_UNSPECIFIED": 0,
		"LOGICAL_OPERATOR_AND":         1,
		"LOGICAL_OPERATOR_OR":          2,
		"LOGICAL_OPERATOR_NOT":         3,
	}
)

func (x LogicalOperator) Enum() *LogicalOperator {
	p := new(LogicalOperator)
	*p = x
	return p
}

func (x LogicalOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_expression_proto_enumTypes[1].Descriptor()
}

func (LogicalOperator) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_expression_proto_enumTypes[1]
}

func (x LogicalOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOperator.Descriptor instead.
func (LogicalOperator) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{1}
}

// Operators supported by null predicates.
type NullPredicateOperator int32

const (
	NullPredicateOperator_NULL_PREDICATE_OPERATOR_UNSPECIFIED NullPredicateOperator = 0
	NullPredicateOperator_NULL_PREDICATE_OPERATOR_IS_NULL     NullPredicateOperator = 1
	NullPredicateOperator_NULL_PREDICATE_OPERATOR_IS_NOT_NULL NullPredicateOperator = 2
)

// Enum value maps for NullPredicateOperator.
var (
	NullPredicateOperator_name = map[int32]string{
		0: "NULL_PREDICATE_OPERATOR_UNSPECIFIED",
		1: "NULL_PREDICATE_OPERATOR_IS_NULL",
		2: "NULL_PREDICATE_OPERATOR_IS_NOT_NULL",
	}
	NullPredicateOperator_value = map[string]int32{
		"NULL_PREDICATE_OPERATOR_UNSPECIFIED": 0,
		"NULL_PREDICATE_OPERATOR_IS_NULL":     1,
		"NULL_PREDICATE_OPERATOR_IS_NOT_NULL": 2,
	}
)

func (x NullPredicateOperator) Enum() *NullPredicateOperator {
	p := new(NullPredicateOperator)
	*p = x
	return p
}

func (x NullPredicateOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullPredicateOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_expression_proto_enumTypes[2].Descriptor()
}

func (NullPredicateOperator) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_expression_proto_enumTypes[2]
}

func (x NullPredicateOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullPredicateOperator.Descriptor instead.
func (NullPredicateOperator) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{2}
}

// Operators supported by pattern expressions.
type PatternOperator int32

const (
	PatternOperator_PATTERN_OPERATOR_UNSPECIFIED PatternOperator = 0
	PatternOperator_PATTERN_OPERATOR_LIKE        PatternOperator = 1
	PatternOperator_PATTERN_OPERATOR_NOT_LIKE    PatternOperator = 2
)

// Enum value maps for PatternOperator.
var (
	PatternOperator_name = map[int32]string{
		0: "PATTERN_OPERATOR_UNSPECIFIED",
		1: "PATTERN_OPERATOR_LIKE",
		2: "PATTERN_OPERATOR_NOT_LIKE",
	}
	PatternOperator_value = map[string]int32{
		"PATTERN_OPERATOR_UNSPECIFIED": 0,
		"PATTERN_OPERATOR_LIKE":        1,
		"PATTERN_OPERATOR_NOT_LIKE":    2,
	}
)

func (x PatternOperator) Enum() *PatternOperator {
	p := new(PatternOperator)
	*p = x
	return p
}

func (x PatternOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_expression_proto_enumTypes[3].Descriptor()
}

func (PatternOperator) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_expression_proto_enumTypes[3]
}

func (x PatternOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatternOperator.Descriptor instead.
func (PatternOperator) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{3}
}

// Expression that may be evaluated by a provider.
//
// Kubling must only send expressions declared as supported through the
// provider capabilities.
type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Expression_Field
	//	*Expression_Literal
	//	*Expression_Comparison
	//	*Expression_Logical
	//	*Expression_NullPredicate
	//	*Expression_FunctionCall
	//	*Expression_Pattern
	Kind          isExpression_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{0}
}

func (x *Expression) GetKind() isExpression_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Expression) GetField() *FieldReference {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Expression) GetLiteral() *Literal {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Literal); ok {
			return x.Literal
		}
	}
	return nil
}

func (x *Expression) GetComparison() *ComparisonExpression {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Comparison); ok {
			return x.Comparison
		}
	}
	return nil
}

func (x *Expression) GetLogical() *LogicalExpression {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Logical); ok {
			return x.Logical
		}
	}
	return nil
}

func (x *Expression) GetNullPredicate() *NullPredicate {
	if x != nil {
		if x, ok := x.Kind.(*Expression_NullPredicate); ok {
			return x.NullPredicate
		}
	}
	return nil
}

func (x *Expression) GetFunctionCall() *FunctionCall {
	if x != nil {
		if x, ok := x.Kind.(*Expression_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Expression) GetPattern() *PatternExpression {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Pattern); ok {
			return x.Pattern
		}
	}
	return nil
}

type isExpression_Kind interface {
	isExpression_Kind()
}

type Expression_Field struct {
	Field *FieldReference `protobuf:"bytes,1,opt,name=field,proto3,oneof"`
}

type Expression_Literal struct {
	Literal *Literal `protobuf:"bytes,2,opt,name=literal,proto3,oneof"`
}

type Expression_Comparison struct {
	Comparison *ComparisonExpression `protobuf:"bytes,3,opt,name=comparison,proto3,oneof"`
}

type Expression_Logical struct {
	Logical *LogicalExpression `protobuf:"bytes,4,opt,name=logical,proto3,oneof"`
}

type Expression_NullPredicate struct {
	NullPredicate *NullPredicate `protobuf:"bytes,5,opt,name=null_predicate,json=nullPredicate,proto3,oneof"`
}

type Expression_FunctionCall struct {
	FunctionCall *FunctionCall `protobuf:"bytes,6,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Expression_Pattern struct {
	Pattern *PatternExpression `protobuf:"bytes,7,opt,name=pattern,proto3,oneof"`
}

func (*Expression_Field) isExpression_Kind() {}

func (*Expression_Literal) isExpression_Kind() {}

func (*Expression_Comparison) isExpression_Kind() {}

func (*Expression_Logical) isExpression_Kind() {}

func (*Expression_NullPredicate) isExpression_Kind() {}

func (*Expression_FunctionCall) isExpression_Kind() {}

func (*Expression_Pattern) isExpression_Kind() {}

// Reference to a logical field in the queried entity.
type FieldReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical field name exposed by the Kubling model.
	//
	// The provider is responsible for mapping this name to its native
	// representation in the data source.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldReference) Reset() {
	*x = FieldReference{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldReference) ProtoMessage() {}

func (x *FieldReference) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldReference.ProtoReflect.Descriptor instead.
func (*FieldReference) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{1}
}

func (x *FieldReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Literal value used in an expression.
type Literal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *v1.Value              `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{2}
}

func (x *Literal) GetValue() *v1.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Comparison between two expressions.
type ComparisonExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      ComparisonOperator     `protobuf:"varint,1,opt,name=operator,proto3,enum=kubling.provider.v1.ComparisonOperator" json:"operator,omitempty"`
	Left          *Expression            `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expression            `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparisonExpression) Reset() {
	*x = ComparisonExpression{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparisonExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparisonExpression) ProtoMessage() {}

func (x *ComparisonExpression) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparisonExpression.ProtoReflect.Descriptor instead.
func (*ComparisonExpression) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{3}
}

func (x *ComparisonExpression) GetOperator() ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return ComparisonOperator_COMPARISON_OPERATOR_UNSPECIFIED
}

func (x *ComparisonExpression) GetLeft() *Expression {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *ComparisonExpression) GetRight() *Expression {
	if x != nil {
		return x.Right
	}
	return nil
}

// Logical composition of boolean expressions.
type LogicalExpression struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Operator LogicalOperator        `protobuf:"varint,1,opt,name=operator,proto3,enum=kubling.provider.v1.LogicalOperator" json:"operator,omitempty"`
	// Expressions combined by the logical operator.
	//
	// AND and OR require at least two operands.
	// NOT requires exactly one operand.
	Operands      []*Expression `protobuf:"bytes,2,rep,name=operands,proto3" json:"operands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalExpression) Reset() {
	*x = LogicalExpression{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalExpression) ProtoMessage() {}

func (x *LogicalExpression) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalExpression.ProtoReflect.Descriptor instead.
func (*LogicalExpression) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{4}
}

func (x *LogicalExpression) GetOperator() LogicalOperator {
	if x != nil {
		return x.Operator
	}
	return LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED
}

func (x *LogicalExpression) GetOperands() []*Expression {
	if x != nil {
		return x.Operands
	}
	return nil
}

// Tests whether an expression is null or not null.
type NullPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      NullPredicateOperator  `protobuf:"varint,1,opt,name=operator,proto3,enum=kubling.provider.v1.NullPredicateOperator" json:"operator,omitempty"`
	Expression    *Expression            `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullPredicate) Reset() {
	*x = NullPredicate{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullPredicate) ProtoMessage() {}

func (x *NullPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullPredicate.ProtoReflect.Descriptor instead.
func (*NullPredicate) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{5}
}

func (x *NullPredicate) GetOperator() NullPredicateOperator {
	if x != nil {
		return x.Operator
	}
	return NullPredicateOperator_NULL_PREDICATE_OPERATOR_UNSPECIFIED
}

func (x *NullPredicate) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

// Pattern comparison between a value and a pattern.
type PatternExpression struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Operator PatternOperator        `protobuf:"varint,1,opt,name=operator,proto3,enum=kubling.provider.v1.PatternOperator" json:"operator,omitempty"`
	// Value to test, normally a field reference.
	Value *Expression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Pattern to apply, normally a string literal.
	Pattern *Expression `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Optional single-character escape used inside the pattern.
	Escape        *string `protobuf:"bytes,4,opt,name=escape,proto3,oneof" json:"escape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternExpression) Reset() {
	*x = PatternExpression{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternExpression) ProtoMessage() {}

func (x *PatternExpression) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternExpression.ProtoReflect.Descriptor instead.
func (*PatternExpression) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{6}
}

func (x *PatternExpression) GetOperator() PatternOperator {
	if x != nil {
		return x.Operator
	}
	return PatternOperator_PATTERN_OPERATOR_UNSPECIFIED
}

func (x *PatternExpression) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PatternExpression) GetPattern() *Expression {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *PatternExpression) GetEscape() string {
	if x != nil && x.Escape != nil {
		return *x.Escape
	}
	return ""
}

// Invocation of a logical Kubling function.
//
// A provider may translate the logical function name to an equivalent native
// operation. Kubling must only push down functions explicitly declared by the
// provider.
type FunctionCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical function name known by Kubling.
	//
	// Native data source function names must not be exposed through this field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Ordered arguments supplied to the function.
	Arguments     []*Expression `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_expression_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_expression_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() []*Expression {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_kubling_provider_v1_expression_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_expression_proto_rawDesc = "" +
	"\n" +
	"$kubling/provider/v1/expression.proto\x12\x13kubling.provider.v1\x1a\x16kubling/v1/value.proto\"\xf7\x03\n" +
	"\n" +
	"Expression\x12;\n" +
	"\x05field\x18\x01 \x01(\v2#.kubling.provider.v1.FieldReferenceH\x00R\x05field\x128\n" +
	"\aliteral\x18\x02 \x01(\v2\x1c.kubling.provider.v1.LiteralH\x00R\aliteral\x12K\n" +
	"\n" +
	"comparison\x18\x03 \x01(\v2).kubling.provider.v1.ComparisonExpressionH\x00R\n" +
	"comparison\x12B\n" +
	"\alogical\x18\x04 \x01(\v2&.kubling.provider.v1.LogicalExpressionH\x00R\alogical\x12K\n" +
	"\x0enull_predicate\x18\x05 \x01(\v2\".kubling.provider.v1.NullPredicateH\x00R\rnullPredicate\x12H\n" +
	"\rfunction_call\x18\x06 \x01(\v2!.kubling.provider.v1.FunctionCallH\x00R\ffunctionCall\x12B\n" +
	"\apattern\x18\a \x01(\v2&.kubling.provider.v1.PatternExpressionH\x00R\apatternB\x06\n" +
	"\x04kind\"$\n" +
	"\x0eFieldReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\aLiteral\x12'\n" +
	"\x05value\x18\x01 \x01(\v2\x11.kubling.v1.ValueR\x05value\"\xc7\x01\n" +
	"\x14ComparisonExpression\x12C\n" +
	"\boperator\x18\x01 \x01(\x0e2'.kubling.provider.v1.ComparisonOperatorR\boperator\x123\n" +
	"\x04left\x18\x02 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x04left\x125\n" +
	"\x05right\x18\x03 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x05right\"\x92\x01\n" +
	"\x11LogicalExpression\x12@\n" +
	"\boperator\x18\x01 \x01(\x0e2$.kubling.provider.v1.LogicalOperatorR\boperator\x12;\n" +
	"\boperands\x18\x02 \x03(\v2\x1f.kubling.provider.v1.ExpressionR\boperands\"\x98\x01\n" +
	"\rNullPredicate\x12F\n" +
	"\boperator\x18\x01 \x01(\x0e2*.kubling.provider.v1.NullPredicateOperatorR\boperator\x12?\n" +
	"\n" +
	"expression\x18\x02 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\n" +
	"expression\"\xef\x01\n" +
	"\x11PatternExpression\x12@\n" +
	"\boperator\x18\x01 \x01(\x0e2$.kubling.provider.v1.PatternOperatorR\boperator\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x05value\x129\n" +
	"\apattern\x18\x03 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\apattern\x12\x1b\n" +
	"\x06escape\x18\x04 \x01(\tH\x00R\x06escape\x88\x01\x01B\t\n" +
	"\a_escape\"a\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\targuments\x18\x02 \x03(\v2\x1f.kubling.provider.v1.ExpressionR\targuments*\x9f\x02\n" +
	"\x12ComparisonOperator\x12#\n" +
	"\x1fCOMPARISON_OPERATOR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMPARISON_OPERATOR_EQUAL\x10\x01\x12!\n" +
	"\x1dCOMPARISON_OPERATOR_NOT_EQUAL\x10\x02\x12!\n" +
	"\x1dCOMPARISON_OPERATOR_LESS_THAN\x10\x03\x12*\n" +
	"&COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL\x10\x04\x12$\n" +
	" COMPARISON_OPERATOR_GREATER_THAN\x10\x05\x12-\n" +
	")COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL\x10\x06*\x80\x01\n" +
	"\x0fLogicalOperator\x12 \n" +
	"\x1cLOGICAL_OPERATOR_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_AND\x10\x01\x12\x17\n" +
	"\x13LOGICAL_OPERATOR_OR\x10\x02\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_NOT\x10\x03*\x8e\x01\n" +
	"\x15NullPredicateOperator\x12'\n" +
	"#NULL_PREDICATE_OPERATOR_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fNULL_PREDICATE_OPERATOR_IS_NULL\x10\x01\x12'\n" +
	"#NULL_PREDICATE_OPERATOR_IS_NOT_NULL\x10\x02*m\n" +
	"\x0fPatternOperator\x12 \n" +
	"\x1cPATTERN_OPERATOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PATTERN_OPERATOR_LIKE\x10\x01\x12\x1d\n" +
	"\x19PATTERN_OPERATOR_NOT_LIKE\x10\x02B\x84\x01\n" +
	"\x19com.kubling.provider.grpcB\x0fExpressionProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_expression_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_expression_proto_rawDescData []byte
)

func file_kubling_provider_v1_expression_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_expression_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_expression_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_expression_proto_rawDesc), len(file_kubling_provider_v1_expression_proto_rawDesc)))
	})
	return file_kubling_provider_v1_expression_proto_rawDescData
}

var file_kubling_provider_v1_expression_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_kubling_provider_v1_expression_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kubling_provider_v1_expression_proto_goTypes = []any{
	(ComparisonOperator)(0),      // 0: kubling.provider.v1.ComparisonOperator
	(LogicalOperator)(0),         // 1: kubling.provider.v1.LogicalOperator
	(NullPredicateOperator)(0),   // 2: kubling.provider.v1.NullPredicateOperator
	(PatternOperator)(0),         // 3: kubling.provider.v1.PatternOperator
	(*Expression)(nil),           // 4: kubling.provider.v1.Expression
	(*FieldReference)(nil),       // 5: kubling.provider.v1.FieldReference
	(*Literal)(nil),              // 6: kubling.provider.v1.Literal
	(*ComparisonExpression)(nil), // 7: kubling.provider.v1.ComparisonExpression
	(*LogicalExpression)(nil),    // 8: kubling.provider.v1.LogicalExpression
	(*NullPredicate)(nil),        // 9: kubling.provider.v1.NullPredicate
	(*PatternExpression)(nil),    // 10: kubling.provider.v1.PatternExpression
	(*FunctionCall)(nil),         // 11: kubling.provider.v1.FunctionCall
	(*v1.Value)(nil),             // 12: kubling.v1.Value
}
var file_kubling_provider_v1_expression_proto_depIdxs = []int32{
	5,  // 0: kubling.provider.v1.Expression.field:type_name -> kubling.provider.v1.FieldReference
	6,  // 1: kubling.provider.v1.Expression.literal:type_name -> kubling.provider.v1.Literal
	7,  // 2: kubling.provider.v1.Expression.comparison:type_name -> kubling.provider.v1.ComparisonExpression
	8,  // 3: kubling.provider.v1.Expression.logical:type_name -> kubling.provider.v1.LogicalExpression
	9,  // 4: kubling.provider.v1.Expression.null_predicate:type_name -> kubling.provider.v1.NullPredicate
	11, // 5: kubling.provider.v1.Expression.function_call:type_name -> kubling.provider.v1.FunctionCall
	10, // 6: kubling.provider.v1.Expression.pattern:type_name -> kubling.provider.v1.PatternExpression
	12, // 7: kubling.provider.v1.Literal.value:type_name -> kubling.v1.Value
	0,  // 8: kubling.provider.v1.ComparisonExpression.operator:type_name -> kubling.provider.v1.ComparisonOperator
	4,  // 9: kubling.provider.v1.ComparisonExpression.left:type_name -> kubling.provider.v1.Expression
	4,  // 10: kubling.provider.v1.ComparisonExpression.right:type_name -> kubling.provider.v1.Expression
	1,  // 11: kubling.provider.v1.LogicalExpression.operator:type_name -> kubling.provider.v1.LogicalOperator
	4,  // 12: kubling.provider.v1.LogicalExpression.operands:type_name -> kubling.provider.v1.Expression
	2,  // 13: kubling.provider.v1.NullPredicate.operator:type_name -> kubling.provider.v1.NullPredicateOperator
	4,  // 14: kubling.provider.v1.NullPredicate.expression:type_name -> kubling.provider.v1.Expression
	3,  // 15: kubling.provider.v1.PatternExpression.operator:type_name -> kubling.provider.v1.PatternOperator
	4,  // 16: kubling.provider.v1.PatternExpression.value:type_name -> kubling.provider.v1.Expression
	4,  // 17: kubling.provider.v1.PatternExpression.pattern:type_name -> kubling.provider.v1.Expression
	4,  // 18: kubling.provider.v1.FunctionCall.arguments:type_name -> kubling.provider.v1.Expression
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_expression_proto_init() }
func file_kubling_provider_v1_expression_proto_init() {
	if File_kubling_provider_v1_expression_proto != nil {
		return
	}
	file_kubling_provider_v1_expression_proto_msgTypes[0].OneofWrappers = []any{
		(*Expression_Field)(nil),
		(*Expression_Literal)(nil),
		(*Expression_Comparison)(nil),
		(*Expression_Logical)(nil),
		(*Expression_NullPredicate)(nil),
		(*Expression_FunctionCall)(nil),
		(*Expression_Pattern)(nil),
	}
	file_kubling_provider_v1_expression_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_expression_proto_rawDesc), len(file_kubling_provider_v1_expression_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_expression_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_expression_proto_depIdxs,
		EnumInfos:         file_kubling_provider_v1_expression_proto_enumTypes,
		MessageInfos:      file_kubling_provider_v1_expression_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_expression_proto = out.File
	file_kubling_provider_v1_expression_proto_goTypes = nil
	file_kubling_provider_v1_expression_proto_depIdxs = nil
}
