// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/lob.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reads an immutable provider-owned LOB through an open logical connection.
//
// Kubling must materialize the complete provider LOB into its own LOB store and
// mint a new client-facing reference. Provider identifiers and references must
// never be forwarded to an external Kubling client.
type ReadLobRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	LobId        string                 `protobuf:"bytes,2,opt,name=lob_id,json=lobId,proto3" json:"lob_id,omitempty"`
	Offset       uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Absent reads to the end; zero requests an empty completed range.
	Length *uint64 `protobuf:"varint,4,opt,name=length,proto3,oneof" json:"length,omitempty"`
	// Zero uses the provider default; otherwise an upper bound in payload bytes.
	MaxChunkBytes uint32 `protobuf:"varint,5,opt,name=max_chunk_bytes,json=maxChunkBytes,proto3" json:"max_chunk_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLobRequest) Reset() {
	*x = ReadLobRequest{}
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLobRequest) ProtoMessage() {}

func (x *ReadLobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLobRequest.ProtoReflect.Descriptor instead.
func (*ReadLobRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_lob_proto_rawDescGZIP(), []int{0}
}

func (x *ReadLobRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ReadLobRequest) GetLobId() string {
	if x != nil {
		return x.LobId
	}
	return ""
}

func (x *ReadLobRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadLobRequest) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ReadLobRequest) GetMaxChunkBytes() uint32 {
	if x != nil {
		return x.MaxChunkBytes
	}
	return 0
}

// One contiguous chunk of a provider-owned LOB.
type ReadLobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Exactly the last response marks the requested range complete, including
	// empty ranges. Final gRPC OK is also required for a complete read.
	EndOfRead     bool `protobuf:"varint,3,opt,name=end_of_read,json=endOfRead,proto3" json:"end_of_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLobResponse) Reset() {
	*x = ReadLobResponse{}
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLobResponse) ProtoMessage() {}

func (x *ReadLobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLobResponse.ProtoReflect.Descriptor instead.
func (*ReadLobResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_lob_proto_rawDescGZIP(), []int{1}
}

func (x *ReadLobResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadLobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadLobResponse) GetEndOfRead() bool {
	if x != nil {
		return x.EndOfRead
	}
	return false
}

// Releases a provider-owned LOB reference.
type ReleaseLobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	LobId         string                 `protobuf:"bytes,2,opt,name=lob_id,json=lobId,proto3" json:"lob_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLobRequest) Reset() {
	*x = ReleaseLobRequest{}
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLobRequest) ProtoMessage() {}

func (x *ReleaseLobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLobRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLobRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_lob_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseLobRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ReleaseLobRequest) GetLobId() string {
	if x != nil {
		return x.LobId
	}
	return ""
}

// Releasing an already released or expired reference is a successful no-op.
type ReleaseLobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLobResponse) Reset() {
	*x = ReleaseLobResponse{}
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLobResponse) ProtoMessage() {}

func (x *ReleaseLobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_lob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLobResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLobResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_lob_proto_rawDescGZIP(), []int{3}
}

var File_kubling_provider_v1_lob_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_lob_proto_rawDesc = "" +
	"\n" +
	"\x1dkubling/provider/v1/lob.proto\x12\x13kubling.provider.v1\"\xb4\x01\n" +
	"\x0eReadLobRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x15\n" +
	"\x06lob_id\x18\x02 \x01(\tR\x05lobId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x1b\n" +
	"\x06length\x18\x04 \x01(\x04H\x00R\x06length\x88\x01\x01\x12&\n" +
	"\x0fmax_chunk_bytes\x18\x05 \x01(\rR\rmaxChunkBytesB\t\n" +
	"\a_length\"]\n" +
	"\x0fReadLobResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\vend_of_read\x18\x03 \x01(\bR\tendOfRead\"O\n" +
	"\x11ReleaseLobRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x15\n" +
	"\x06lob_id\x18\x02 \x01(\tR\x05lobId\"\x14\n" +
	"\x12ReleaseLobResponseB}\n" +
	"\x19com.kubling.provider.grpcB\bLobProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_lob_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_lob_proto_rawDescData []byte
)

func file_kubling_provider_v1_lob_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_lob_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_lob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_lob_proto_rawDesc), len(file_kubling_provider_v1_lob_proto_rawDesc)))
	})
	return file_kubling_provider_v1_lob_proto_rawDescData
}

var file_kubling_provider_v1_lob_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubling_provider_v1_lob_proto_goTypes = []any{
	(*ReadLobRequest)(nil),     // 0: kubling.provider.v1.ReadLobRequest
	(*ReadLobResponse)(nil),    // 1: kubling.provider.v1.ReadLobResponse
	(*ReleaseLobRequest)(nil),  // 2: kubling.provider.v1.ReleaseLobRequest
	(*ReleaseLobResponse)(nil), // 3: kubling.provider.v1.ReleaseLobResponse
}
var file_kubling_provider_v1_lob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_lob_proto_init() }
func file_kubling_provider_v1_lob_proto_init() {
	if File_kubling_provider_v1_lob_proto != nil {
		return
	}
	file_kubling_provider_v1_lob_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_lob_proto_rawDesc), len(file_kubling_provider_v1_lob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_lob_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_lob_proto_depIdxs,
		MessageInfos:      file_kubling_provider_v1_lob_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_lob_proto = out.File
	file_kubling_provider_v1_lob_proto_goTypes = nil
	file_kubling_provider_v1_lob_proto_depIdxs = nil
}
