// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/metadata.proto

package providerv1

import (
	v1 "github.com/kubling-community/kubling-grpc/sdk-go/kubling/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableKind int32

const (
	TableKind_TABLE_KIND_UNSPECIFIED TableKind = 0
	TableKind_TABLE_KIND_TABLE       TableKind = 1
	TableKind_TABLE_KIND_VIEW        TableKind = 2
)

// Enum value maps for TableKind.
var (
	TableKind_name = map[int32]string{
		0: "TABLE_KIND_UNSPECIFIED",
		1: "TABLE_KIND_TABLE",
		2: "TABLE_KIND_VIEW",
	}
	TableKind_value = map[string]int32{
		"TABLE_KIND_UNSPECIFIED": 0,
		"TABLE_KIND_TABLE":       1,
		"TABLE_KIND_VIEW":        2,
	}
)

func (x TableKind) Enum() *TableKind {
	p := new(TableKind)
	*p = x
	return p
}

func (x TableKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[0].Descriptor()
}

func (TableKind) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[0]
}

func (x TableKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableKind.Descriptor instead.
func (TableKind) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{0}
}

type KeyKind int32

const (
	KeyKind_KEY_KIND_UNSPECIFIED KeyKind = 0
	KeyKind_KEY_KIND_PRIMARY     KeyKind = 1
	KeyKind_KEY_KIND_UNIQUE      KeyKind = 2
	KeyKind_KEY_KIND_INDEX       KeyKind = 3
	KeyKind_KEY_KIND_FOREIGN     KeyKind = 4
)

// Enum value maps for KeyKind.
var (
	KeyKind_name = map[int32]string{
		0: "KEY_KIND_UNSPECIFIED",
		1: "KEY_KIND_PRIMARY",
		2: "KEY_KIND_UNIQUE",
		3: "KEY_KIND_INDEX",
		4: "KEY_KIND_FOREIGN",
	}
	KeyKind_value = map[string]int32{
		"KEY_KIND_UNSPECIFIED": 0,
		"KEY_KIND_PRIMARY":     1,
		"KEY_KIND_UNIQUE":      2,
		"KEY_KIND_INDEX":       3,
		"KEY_KIND_FOREIGN":     4,
	}
)

func (x KeyKind) Enum() *KeyKind {
	p := new(KeyKind)
	*p = x
	return p
}

func (x KeyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[1].Descriptor()
}

func (KeyKind) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[1]
}

func (x KeyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyKind.Descriptor instead.
func (KeyKind) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{1}
}

type ColumnSearchability int32

const (
	ColumnSearchability_COLUMN_SEARCHABILITY_UNSPECIFIED  ColumnSearchability = 0
	ColumnSearchability_COLUMN_SEARCHABILITY_UNSEARCHABLE ColumnSearchability = 1
	ColumnSearchability_COLUMN_SEARCHABILITY_EQUALITY     ColumnSearchability = 2
	ColumnSearchability_COLUMN_SEARCHABILITY_ORDERED      ColumnSearchability = 3
	ColumnSearchability_COLUMN_SEARCHABILITY_ALL          ColumnSearchability = 4
)

// Enum value maps for ColumnSearchability.
var (
	ColumnSearchability_name = map[int32]string{
		0: "COLUMN_SEARCHABILITY_UNSPECIFIED",
		1: "COLUMN_SEARCHABILITY_UNSEARCHABLE",
		2: "COLUMN_SEARCHABILITY_EQUALITY",
		3: "COLUMN_SEARCHABILITY_ORDERED",
		4: "COLUMN_SEARCHABILITY_ALL",
	}
	ColumnSearchability_value = map[string]int32{
		"COLUMN_SEARCHABILITY_UNSPECIFIED":  0,
		"COLUMN_SEARCHABILITY_UNSEARCHABLE": 1,
		"COLUMN_SEARCHABILITY_EQUALITY":     2,
		"COLUMN_SEARCHABILITY_ORDERED":      3,
		"COLUMN_SEARCHABILITY_ALL":          4,
	}
)

func (x ColumnSearchability) Enum() *ColumnSearchability {
	p := new(ColumnSearchability)
	*p = x
	return p
}

func (x ColumnSearchability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnSearchability) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[2].Descriptor()
}

func (ColumnSearchability) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[2]
}

func (x ColumnSearchability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnSearchability.Descriptor instead.
func (ColumnSearchability) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{2}
}

type SyntheticCardinality int32

const (
	SyntheticCardinality_SYNTHETIC_CARDINALITY_UNSPECIFIED SyntheticCardinality = 0
	SyntheticCardinality_SYNTHETIC_CARDINALITY_OBJECT      SyntheticCardinality = 1
	SyntheticCardinality_SYNTHETIC_CARDINALITY_ARRAY       SyntheticCardinality = 2
)

// Enum value maps for SyntheticCardinality.
var (
	SyntheticCardinality_name = map[int32]string{
		0: "SYNTHETIC_CARDINALITY_UNSPECIFIED",
		1: "SYNTHETIC_CARDINALITY_OBJECT",
		2: "SYNTHETIC_CARDINALITY_ARRAY",
	}
	SyntheticCardinality_value = map[string]int32{
		"SYNTHETIC_CARDINALITY_UNSPECIFIED": 0,
		"SYNTHETIC_CARDINALITY_OBJECT":      1,
		"SYNTHETIC_CARDINALITY_ARRAY":       2,
	}
)

func (x SyntheticCardinality) Enum() *SyntheticCardinality {
	p := new(SyntheticCardinality)
	*p = x
	return p
}

func (x SyntheticCardinality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyntheticCardinality) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[3].Descriptor()
}

func (SyntheticCardinality) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[3]
}

func (x SyntheticCardinality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyntheticCardinality.Descriptor instead.
func (SyntheticCardinality) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{3}
}

type ParentColumnScope int32

const (
	ParentColumnScope_PARENT_COLUMN_SCOPE_UNSPECIFIED ParentColumnScope = 0
	ParentColumnScope_PARENT_COLUMN_SCOPE_IMMEDIATE   ParentColumnScope = 1
	ParentColumnScope_PARENT_COLUMN_SCOPE_ROOT        ParentColumnScope = 2
)

// Enum value maps for ParentColumnScope.
var (
	ParentColumnScope_name = map[int32]string{
		0: "PARENT_COLUMN_SCOPE_UNSPECIFIED",
		1: "PARENT_COLUMN_SCOPE_IMMEDIATE",
		2: "PARENT_COLUMN_SCOPE_ROOT",
	}
	ParentColumnScope_value = map[string]int32{
		"PARENT_COLUMN_SCOPE_UNSPECIFIED": 0,
		"PARENT_COLUMN_SCOPE_IMMEDIATE":   1,
		"PARENT_COLUMN_SCOPE_ROOT":        2,
	}
)

func (x ParentColumnScope) Enum() *ParentColumnScope {
	p := new(ParentColumnScope)
	*p = x
	return p
}

func (x ParentColumnScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParentColumnScope) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[4].Descriptor()
}

func (ParentColumnScope) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[4]
}

func (x ParentColumnScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParentColumnScope.Descriptor instead.
func (ParentColumnScope) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{4}
}

type SyntheticMutationStrategy int32

const (
	SyntheticMutationStrategy_SYNTHETIC_MUTATION_STRATEGY_UNSPECIFIED SyntheticMutationStrategy = 0
	// Kubling performs its read-modify-write flow against the physical parent
	// document for inserts, updates and deletes.
	SyntheticMutationStrategy_SYNTHETIC_MUTATION_STRATEGY_PARENT_DOCUMENT_REWRITE SyntheticMutationStrategy = 1
)

// Enum value maps for SyntheticMutationStrategy.
var (
	SyntheticMutationStrategy_name = map[int32]string{
		0: "SYNTHETIC_MUTATION_STRATEGY_UNSPECIFIED",
		1: "SYNTHETIC_MUTATION_STRATEGY_PARENT_DOCUMENT_REWRITE",
	}
	SyntheticMutationStrategy_value = map[string]int32{
		"SYNTHETIC_MUTATION_STRATEGY_UNSPECIFIED":             0,
		"SYNTHETIC_MUTATION_STRATEGY_PARENT_DOCUMENT_REWRITE": 1,
	}
)

func (x SyntheticMutationStrategy) Enum() *SyntheticMutationStrategy {
	p := new(SyntheticMutationStrategy)
	*p = x
	return p
}

func (x SyntheticMutationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyntheticMutationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_metadata_proto_enumTypes[5].Descriptor()
}

func (SyntheticMutationStrategy) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_metadata_proto_enumTypes[5]
}

func (x SyntheticMutationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyntheticMutationStrategy.Descriptor instead.
func (SyntheticMutationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{5}
}

// Provider-neutral relational metadata exposed to Kubling.
//
// This structure intentionally models logical relational concepts rather than
// Kubling core classes or native data source metadata. Provider-specific information
// may be preserved through properties without coupling the engine to the
// provider implementation.
type SchemaMetadata struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tables []*TableMetadata       `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	// Provider-defined schema properties.
	//
	// Property values must not contain credentials or other secrets.
	Properties map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Logical namespaces exposed by the provider.
	//
	// Namespace names are provider-defined opaque logical groupings. They may
	// represent concepts such as a catalog, schema, keyspace, bucket, resource
	// path or API domain without exposing physical topology to Kubling.
	Namespaces    []*NamespaceMetadata `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaMetadata) Reset() {
	*x = SchemaMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaMetadata) ProtoMessage() {}

func (x *SchemaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaMetadata.ProtoReflect.Descriptor instead.
func (*SchemaMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaMetadata) GetTables() []*TableMetadata {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *SchemaMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SchemaMetadata) GetNamespaces() []*NamespaceMetadata {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// Logical namespace exposed by a provider.
type NamespaceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque logical name that uniquely identifies the namespace.
	//
	// Kubling returns this value unchanged when referencing contained entities.
	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Annotation string `protobuf:"bytes,2,opt,name=annotation,proto3" json:"annotation,omitempty"`
	// Provider-defined namespace properties.
	//
	// Property values must not contain credentials or other secrets.
	Properties    map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceMetadata) Reset() {
	*x = NamespaceMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceMetadata) ProtoMessage() {}

func (x *NamespaceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceMetadata.ProtoReflect.Descriptor instead.
func (*NamespaceMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceMetadata) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

func (x *NamespaceMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Logical table or view exposed by a provider.
type TableMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name visible to Kubling queries.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Native source name when it differs from the logical name.
	SourceName string            `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Kind       TableKind         `protobuf:"varint,3,opt,name=kind,proto3,enum=kubling.provider.v1.TableKind" json:"kind,omitempty"`
	Columns    []*ColumnMetadata `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	Keys       []*KeyMetadata    `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	// Whether Kubling may plan mutations against this table.
	Updatable  *bool  `protobuf:"varint,6,opt,name=updatable,proto3,oneof" json:"updatable,omitempty"`
	Annotation string `protobuf:"bytes,7,opt,name=annotation,proto3" json:"annotation,omitempty"`
	// Provider-defined table properties.
	//
	// Properties may preserve source semantics not represented by the common
	// model. Values must not contain credentials or other secrets.
	Properties map[string]string `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Logical namespace containing this table.
	//
	// An empty value places the table at the provider root.
	Namespace string `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Defines this table as a relational projection over a JSON column from
	// another table in the same SchemaMetadata.
	//
	// Providers may leave this unset. Kubling may add synthetic tables while
	// composing the final logical schema without involving provider execution.
	Synthetic     *SyntheticTableMetadata `protobuf:"bytes,10,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableMetadata) Reset() {
	*x = TableMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMetadata) ProtoMessage() {}

func (x *TableMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMetadata.ProtoReflect.Descriptor instead.
func (*TableMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *TableMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableMetadata) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *TableMetadata) GetKind() TableKind {
	if x != nil {
		return x.Kind
	}
	return TableKind_TABLE_KIND_UNSPECIFIED
}

func (x *TableMetadata) GetColumns() []*ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableMetadata) GetKeys() []*KeyMetadata {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TableMetadata) GetUpdatable() bool {
	if x != nil && x.Updatable != nil {
		return *x.Updatable
	}
	return false
}

func (x *TableMetadata) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

func (x *TableMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *TableMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableMetadata) GetSynthetic() *SyntheticTableMetadata {
	if x != nil {
		return x.Synthetic
	}
	return nil
}

// Logical column exposed by a table.
type ColumnMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical name visible to Kubling queries.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Native source name when it differs from the logical name.
	SourceName string `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Canonical Kubling type used for transport and planning.
	Type v1.ValueType `protobuf:"varint,3,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	// Native source type retained for diagnostics and provider-specific logic.
	NativeType      string `protobuf:"bytes,4,opt,name=native_type,json=nativeType,proto3" json:"native_type,omitempty"`
	Nullable        *bool  `protobuf:"varint,5,opt,name=nullable,proto3,oneof" json:"nullable,omitempty"`
	Updatable       *bool  `protobuf:"varint,6,opt,name=updatable,proto3,oneof" json:"updatable,omitempty"`
	AutoIncremented *bool  `protobuf:"varint,7,opt,name=auto_incremented,json=autoIncremented,proto3,oneof" json:"auto_incremented,omitempty"`
	// Optional type dimensions. Zero is a valid explicit value when present.
	Length    *int32 `protobuf:"varint,8,opt,name=length,proto3,oneof" json:"length,omitempty"`
	Precision *int32 `protobuf:"varint,9,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	Scale     *int32 `protobuf:"varint,10,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	// Optional Kubling expression used as the column default.
	DefaultExpression string              `protobuf:"bytes,11,opt,name=default_expression,json=defaultExpression,proto3" json:"default_expression,omitempty"`
	Searchability     ColumnSearchability `protobuf:"varint,12,opt,name=searchability,proto3,enum=kubling.provider.v1.ColumnSearchability" json:"searchability,omitempty"`
	Annotation        string              `protobuf:"bytes,13,opt,name=annotation,proto3" json:"annotation,omitempty"`
	// Provider-defined column properties.
	//
	// Property values must not contain credentials or other secrets.
	Properties    map[string]string `protobuf:"bytes,14,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMetadata) Reset() {
	*x = ColumnMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata) ProtoMessage() {}

func (x *ColumnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata.ProtoReflect.Descriptor instead.
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnMetadata) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ColumnMetadata) GetType() v1.ValueType {
	if x != nil {
		return x.Type
	}
	return v1.ValueType(0)
}

func (x *ColumnMetadata) GetNativeType() string {
	if x != nil {
		return x.NativeType
	}
	return ""
}

func (x *ColumnMetadata) GetNullable() bool {
	if x != nil && x.Nullable != nil {
		return *x.Nullable
	}
	return false
}

func (x *ColumnMetadata) GetUpdatable() bool {
	if x != nil && x.Updatable != nil {
		return *x.Updatable
	}
	return false
}

func (x *ColumnMetadata) GetAutoIncremented() bool {
	if x != nil && x.AutoIncremented != nil {
		return *x.AutoIncremented
	}
	return false
}

func (x *ColumnMetadata) GetLength() int32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ColumnMetadata) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *ColumnMetadata) GetScale() int32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *ColumnMetadata) GetDefaultExpression() string {
	if x != nil {
		return x.DefaultExpression
	}
	return ""
}

func (x *ColumnMetadata) GetSearchability() ColumnSearchability {
	if x != nil {
		return x.Searchability
	}
	return ColumnSearchability_COLUMN_SEARCHABILITY_UNSPECIFIED
}

func (x *ColumnMetadata) GetAnnotation() string {
	if x != nil {
		return x.Annotation
	}
	return ""
}

func (x *ColumnMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Derivation of a synthetic table from a JSON column in a parent table.
//
// The relational table itself is the containing TableMetadata, so physical and
// synthetic tables share the same namespace, keys, columns and update policy.
// Parent tables may themselves be synthetic.
type SyntheticTableMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent table in the same SchemaMetadata.
	Parent *TableReference `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// JSON column in the parent table from which rows are expanded.
	SourceColumn string `protobuf:"bytes,2,opt,name=source_column,json=sourceColumn,proto3" json:"source_column,omitempty"`
	// JSON path evaluated relative to source_column.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Shape produced by evaluating path.
	Cardinality SyntheticCardinality `protobuf:"varint,4,opt,name=cardinality,proto3,enum=kubling.provider.v1.SyntheticCardinality" json:"cardinality,omitempty"`
	// Origin of every derived or inherited relational column.
	ColumnBindings []*SyntheticColumnBinding `protobuf:"bytes,5,rep,name=column_bindings,json=columnBindings,proto3" json:"column_bindings,omitempty"`
	// Mutation behavior implemented by Kubling for this derived table.
	Mutations     *SyntheticMutationMetadata `protobuf:"bytes,6,opt,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyntheticTableMetadata) Reset() {
	*x = SyntheticTableMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticTableMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticTableMetadata) ProtoMessage() {}

func (x *SyntheticTableMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticTableMetadata.ProtoReflect.Descriptor instead.
func (*SyntheticTableMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *SyntheticTableMetadata) GetParent() *TableReference {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *SyntheticTableMetadata) GetSourceColumn() string {
	if x != nil {
		return x.SourceColumn
	}
	return ""
}

func (x *SyntheticTableMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyntheticTableMetadata) GetCardinality() SyntheticCardinality {
	if x != nil {
		return x.Cardinality
	}
	return SyntheticCardinality_SYNTHETIC_CARDINALITY_UNSPECIFIED
}

func (x *SyntheticTableMetadata) GetColumnBindings() []*SyntheticColumnBinding {
	if x != nil {
		return x.ColumnBindings
	}
	return nil
}

func (x *SyntheticTableMetadata) GetMutations() *SyntheticMutationMetadata {
	if x != nil {
		return x.Mutations
	}
	return nil
}

// Logical table identity inside the same schema metadata.
type TableReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableReference) Reset() {
	*x = TableReference{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReference) ProtoMessage() {}

func (x *TableReference) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReference.ProtoReflect.Descriptor instead.
func (*TableReference) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *TableReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Maps one synthetic-table column to its document or parent origin.
type SyntheticColumnBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name declared in the containing TableMetadata.
	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*SyntheticColumnBinding_Document
	//	*SyntheticColumnBinding_Parent
	//	*SyntheticColumnBinding_Ordinality
	Source        isSyntheticColumnBinding_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyntheticColumnBinding) Reset() {
	*x = SyntheticColumnBinding{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticColumnBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticColumnBinding) ProtoMessage() {}

func (x *SyntheticColumnBinding) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticColumnBinding.ProtoReflect.Descriptor instead.
func (*SyntheticColumnBinding) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *SyntheticColumnBinding) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *SyntheticColumnBinding) GetSource() isSyntheticColumnBinding_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SyntheticColumnBinding) GetDocument() *DocumentColumnBinding {
	if x != nil {
		if x, ok := x.Source.(*SyntheticColumnBinding_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *SyntheticColumnBinding) GetParent() *ParentColumnBinding {
	if x != nil {
		if x, ok := x.Source.(*SyntheticColumnBinding_Parent); ok {
			return x.Parent
		}
	}
	return nil
}

func (x *SyntheticColumnBinding) GetOrdinality() *OrdinalityColumnBinding {
	if x != nil {
		if x, ok := x.Source.(*SyntheticColumnBinding_Ordinality); ok {
			return x.Ordinality
		}
	}
	return nil
}

type isSyntheticColumnBinding_Source interface {
	isSyntheticColumnBinding_Source()
}

type SyntheticColumnBinding_Document struct {
	// Value extracted from each expanded JSON element.
	Document *DocumentColumnBinding `protobuf:"bytes,2,opt,name=document,proto3,oneof"`
}

type SyntheticColumnBinding_Parent struct {
	// Value inherited from an ancestor relational row.
	Parent *ParentColumnBinding `protobuf:"bytes,3,opt,name=parent,proto3,oneof"`
}

type SyntheticColumnBinding_Ordinality struct {
	// One-based position of the expanded JSON element.
	Ordinality *OrdinalityColumnBinding `protobuf:"bytes,4,opt,name=ordinality,proto3,oneof"`
}

func (*SyntheticColumnBinding_Document) isSyntheticColumnBinding_Source() {}

func (*SyntheticColumnBinding_Parent) isSyntheticColumnBinding_Source() {}

func (*SyntheticColumnBinding_Ordinality) isSyntheticColumnBinding_Source() {}

// Extracts a value relative to the current expanded JSON element.
type DocumentColumnBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentColumnBinding) Reset() {
	*x = DocumentColumnBinding{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentColumnBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentColumnBinding) ProtoMessage() {}

func (x *DocumentColumnBinding) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentColumnBinding.ProtoReflect.Descriptor instead.
func (*DocumentColumnBinding) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentColumnBinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Inherits a column from the immediate parent or root physical row.
type ParentColumnBinding struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Column string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Scope  ParentColumnScope      `protobuf:"varint,2,opt,name=scope,proto3,enum=kubling.provider.v1.ParentColumnScope" json:"scope,omitempty"`
	// True when this value identifies the parent array element while mutating a
	// nested synthetic table.
	IdentifiesParentElement bool `protobuf:"varint,3,opt,name=identifies_parent_element,json=identifiesParentElement,proto3" json:"identifies_parent_element,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ParentColumnBinding) Reset() {
	*x = ParentColumnBinding{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentColumnBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentColumnBinding) ProtoMessage() {}

func (x *ParentColumnBinding) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentColumnBinding.ProtoReflect.Descriptor instead.
func (*ParentColumnBinding) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *ParentColumnBinding) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ParentColumnBinding) GetScope() ParentColumnScope {
	if x != nil {
		return x.Scope
	}
	return ParentColumnScope_PARENT_COLUMN_SCOPE_UNSPECIFIED
}

func (x *ParentColumnBinding) GetIdentifiesParentElement() bool {
	if x != nil {
		return x.IdentifiesParentElement
	}
	return false
}

// Marks a relational column as the ordinal position of an expanded element.
type OrdinalityColumnBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdinalityColumnBinding) Reset() {
	*x = OrdinalityColumnBinding{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdinalityColumnBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinalityColumnBinding) ProtoMessage() {}

func (x *OrdinalityColumnBinding) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinalityColumnBinding.ProtoReflect.Descriptor instead.
func (*OrdinalityColumnBinding) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{9}
}

// Kubling-owned mutation contract for a synthetic table.
//
// Kubling may locate the parent row, modify the nested document and submit the
// resulting parent mutation through the normal provider mutation API.
type SyntheticMutationMetadata struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Strategy SyntheticMutationStrategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=kubling.provider.v1.SyntheticMutationStrategy" json:"strategy,omitempty"`
	// Presence distinguishes an explicit policy from a Core default.
	Insertable      *bool `protobuf:"varint,2,opt,name=insertable,proto3,oneof" json:"insertable,omitempty"`
	Updatable       *bool `protobuf:"varint,3,opt,name=updatable,proto3,oneof" json:"updatable,omitempty"`
	Deletable       *bool `protobuf:"varint,4,opt,name=deletable,proto3,oneof" json:"deletable,omitempty"`
	AllowBulkInsert *bool `protobuf:"varint,5,opt,name=allow_bulk_insert,json=allowBulkInsert,proto3,oneof" json:"allow_bulk_insert,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyntheticMutationMetadata) Reset() {
	*x = SyntheticMutationMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticMutationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticMutationMetadata) ProtoMessage() {}

func (x *SyntheticMutationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticMutationMetadata.ProtoReflect.Descriptor instead.
func (*SyntheticMutationMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *SyntheticMutationMetadata) GetStrategy() SyntheticMutationStrategy {
	if x != nil {
		return x.Strategy
	}
	return SyntheticMutationStrategy_SYNTHETIC_MUTATION_STRATEGY_UNSPECIFIED
}

func (x *SyntheticMutationMetadata) GetInsertable() bool {
	if x != nil && x.Insertable != nil {
		return *x.Insertable
	}
	return false
}

func (x *SyntheticMutationMetadata) GetUpdatable() bool {
	if x != nil && x.Updatable != nil {
		return *x.Updatable
	}
	return false
}

func (x *SyntheticMutationMetadata) GetDeletable() bool {
	if x != nil && x.Deletable != nil {
		return *x.Deletable
	}
	return false
}

func (x *SyntheticMutationMetadata) GetAllowBulkInsert() bool {
	if x != nil && x.AllowBulkInsert != nil {
		return *x.AllowBulkInsert
	}
	return false
}

// Ordered relational key definition.
type KeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  KeyKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=kubling.provider.v1.KeyKind" json:"kind,omitempty"`
	// Logical column names in key order.
	Columns []string `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	// Logical referenced table and columns for foreign keys.
	ReferencedTable   string            `protobuf:"bytes,4,opt,name=referenced_table,json=referencedTable,proto3" json:"referenced_table,omitempty"`
	ReferencedColumns []string          `protobuf:"bytes,5,rep,name=referenced_columns,json=referencedColumns,proto3" json:"referenced_columns,omitempty"`
	Properties        map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KeyMetadata) Reset() {
	*x = KeyMetadata{}
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMetadata) ProtoMessage() {}

func (x *KeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMetadata.ProtoReflect.Descriptor instead.
func (*KeyMetadata) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *KeyMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyMetadata) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_KEY_KIND_UNSPECIFIED
}

func (x *KeyMetadata) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *KeyMetadata) GetReferencedTable() string {
	if x != nil {
		return x.ReferencedTable
	}
	return ""
}

func (x *KeyMetadata) GetReferencedColumns() []string {
	if x != nil {
		return x.ReferencedColumns
	}
	return nil
}

func (x *KeyMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_kubling_provider_v1_metadata_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\"kubling/provider/v1/metadata.proto\x12\x13kubling.provider.v1\x1a\x16kubling/v1/value.proto\"\xa8\x02\n" +
	"\x0eSchemaMetadata\x12:\n" +
	"\x06tables\x18\x01 \x03(\v2\".kubling.provider.v1.TableMetadataR\x06tables\x12S\n" +
	"\n" +
	"properties\x18\x02 \x03(\v23.kubling.provider.v1.SchemaMetadata.PropertiesEntryR\n" +
	"properties\x12F\n" +
	"\n" +
	"namespaces\x18\x03 \x03(\v2&.kubling.provider.v1.NamespaceMetadataR\n" +
	"namespaces\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x11NamespaceMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"annotation\x18\x02 \x01(\tR\n" +
	"annotation\x12V\n" +
	"\n" +
	"properties\x18\x03 \x03(\v26.kubling.provider.v1.NamespaceMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x04\n" +
	"\rTableMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x122\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1e.kubling.provider.v1.TableKindR\x04kind\x12=\n" +
	"\acolumns\x18\x04 \x03(\v2#.kubling.provider.v1.ColumnMetadataR\acolumns\x124\n" +
	"\x04keys\x18\x05 \x03(\v2 .kubling.provider.v1.KeyMetadataR\x04keys\x12!\n" +
	"\tupdatable\x18\x06 \x01(\bH\x00R\tupdatable\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"annotation\x18\a \x01(\tR\n" +
	"annotation\x12R\n" +
	"\n" +
	"properties\x18\b \x03(\v22.kubling.provider.v1.TableMetadata.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12I\n" +
	"\tsynthetic\x18\n" +
	" \x01(\v2+.kubling.provider.v1.SyntheticTableMetadataR\tsynthetic\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_updatable\"\xe6\x05\n" +
	"\x0eColumnMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\x12\x1f\n" +
	"\vnative_type\x18\x04 \x01(\tR\n" +
	"nativeType\x12\x1f\n" +
	"\bnullable\x18\x05 \x01(\bH\x00R\bnullable\x88\x01\x01\x12!\n" +
	"\tupdatable\x18\x06 \x01(\bH\x01R\tupdatable\x88\x01\x01\x12.\n" +
	"\x10auto_incremented\x18\a \x01(\bH\x02R\x0fautoIncremented\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\b \x01(\x05H\x03R\x06length\x88\x01\x01\x12!\n" +
	"\tprecision\x18\t \x01(\x05H\x04R\tprecision\x88\x01\x01\x12\x19\n" +
	"\x05scale\x18\n" +
	" \x01(\x05H\x05R\x05scale\x88\x01\x01\x12-\n" +
	"\x12default_expression\x18\v \x01(\tR\x11defaultExpression\x12N\n" +
	"\rsearchability\x18\f \x01(\x0e2(.kubling.provider.v1.ColumnSearchabilityR\rsearchability\x12\x1e\n" +
	"\n" +
	"annotation\x18\r \x01(\tR\n" +
	"annotation\x12S\n" +
	"\n" +
	"properties\x18\x0e \x03(\v23.kubling.provider.v1.ColumnMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_nullableB\f\n" +
	"\n" +
	"_updatableB\x13\n" +
	"\x11_auto_incrementedB\t\n" +
	"\a_lengthB\f\n" +
	"\n" +
	"_precisionB\b\n" +
	"\x06_scale\"\xff\x02\n" +
	"\x16SyntheticTableMetadata\x12;\n" +
	"\x06parent\x18\x01 \x01(\v2#.kubling.provider.v1.TableReferenceR\x06parent\x12#\n" +
	"\rsource_column\x18\x02 \x01(\tR\fsourceColumn\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12K\n" +
	"\vcardinality\x18\x04 \x01(\x0e2).kubling.provider.v1.SyntheticCardinalityR\vcardinality\x12T\n" +
	"\x0fcolumn_bindings\x18\x05 \x03(\v2+.kubling.provider.v1.SyntheticColumnBindingR\x0ecolumnBindings\x12L\n" +
	"\tmutations\x18\x06 \x01(\v2..kubling.provider.v1.SyntheticMutationMetadataR\tmutations\"B\n" +
	"\x0eTableReference\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x98\x02\n" +
	"\x16SyntheticColumnBinding\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12H\n" +
	"\bdocument\x18\x02 \x01(\v2*.kubling.provider.v1.DocumentColumnBindingH\x00R\bdocument\x12B\n" +
	"\x06parent\x18\x03 \x01(\v2(.kubling.provider.v1.ParentColumnBindingH\x00R\x06parent\x12N\n" +
	"\n" +
	"ordinality\x18\x04 \x01(\v2,.kubling.provider.v1.OrdinalityColumnBindingH\x00R\n" +
	"ordinalityB\b\n" +
	"\x06source\"+\n" +
	"\x15DocumentColumnBinding\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa7\x01\n" +
	"\x13ParentColumnBinding\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12<\n" +
	"\x05scope\x18\x02 \x01(\x0e2&.kubling.provider.v1.ParentColumnScopeR\x05scope\x12:\n" +
	"\x19identifies_parent_element\x18\x03 \x01(\bR\x17identifiesParentElement\"\x19\n" +
	"\x17OrdinalityColumnBinding\"\xc4\x02\n" +
	"\x19SyntheticMutationMetadata\x12J\n" +
	"\bstrategy\x18\x01 \x01(\x0e2..kubling.provider.v1.SyntheticMutationStrategyR\bstrategy\x12#\n" +
	"\n" +
	"insertable\x18\x02 \x01(\bH\x00R\n" +
	"insertable\x88\x01\x01\x12!\n" +
	"\tupdatable\x18\x03 \x01(\bH\x01R\tupdatable\x88\x01\x01\x12!\n" +
	"\tdeletable\x18\x04 \x01(\bH\x02R\tdeletable\x88\x01\x01\x12/\n" +
	"\x11allow_bulk_insert\x18\x05 \x01(\bH\x03R\x0fallowBulkInsert\x88\x01\x01B\r\n" +
	"\v_insertableB\f\n" +
	"\n" +
	"_updatableB\f\n" +
	"\n" +
	"_deletableB\x14\n" +
	"\x12_allow_bulk_insert\"\xd8\x02\n" +
	"\vKeyMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.kubling.provider.v1.KeyKindR\x04kind\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12)\n" +
	"\x10referenced_table\x18\x04 \x01(\tR\x0freferencedTable\x12-\n" +
	"\x12referenced_columns\x18\x05 \x03(\tR\x11referencedColumns\x12P\n" +
	"\n" +
	"properties\x18\x06 \x03(\v20.kubling.provider.v1.KeyMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*R\n" +
	"\tTableKind\x12\x1a\n" +
	"\x16TABLE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TABLE_KIND_TABLE\x10\x01\x12\x13\n" +
	"\x0fTABLE_KIND_VIEW\x10\x02*x\n" +
	"\aKeyKind\x12\x18\n" +
	"\x14KEY_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KEY_KIND_PRIMARY\x10\x01\x12\x13\n" +
	"\x0fKEY_KIND_UNIQUE\x10\x02\x12\x12\n" +
	"\x0eKEY_KIND_INDEX\x10\x03\x12\x14\n" +
	"\x10KEY_KIND_FOREIGN\x10\x04*\xc5\x01\n" +
	"\x13ColumnSearchability\x12$\n" +
	" COLUMN_SEARCHABILITY_UNSPECIFIED\x10\x00\x12%\n" +
	"!COLUMN_SEARCHABILITY_UNSEARCHABLE\x10\x01\x12!\n" +
	"\x1dCOLUMN_SEARCHABILITY_EQUALITY\x10\x02\x12 \n" +
	"\x1cCOLUMN_SEARCHABILITY_ORDERED\x10\x03\x12\x1c\n" +
	"\x18COLUMN_SEARCHABILITY_ALL\x10\x04*\x80\x01\n" +
	"\x14SyntheticCardinality\x12%\n" +
	"!SYNTHETIC_CARDINALITY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSYNTHETIC_CARDINALITY_OBJECT\x10\x01\x12\x1f\n" +
	"\x1bSYNTHETIC_CARDINALITY_ARRAY\x10\x02*y\n" +
	"\x11ParentColumnScope\x12#\n" +
	"\x1fPARENT_COLUMN_SCOPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPARENT_COLUMN_SCOPE_IMMEDIATE\x10\x01\x12\x1c\n" +
	"\x18PARENT_COLUMN_SCOPE_ROOT\x10\x02*\x81\x01\n" +
	"\x19SyntheticMutationStrategy\x12+\n" +
	"'SYNTHETIC_MUTATION_STRATEGY_UNSPECIFIED\x10\x00\x127\n" +
	"3SYNTHETIC_MUTATION_STRATEGY_PARENT_DOCUMENT_REWRITE\x10\x01B\x82\x01\n" +
	"\x19com.kubling.provider.grpcB\rMetadataProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_metadata_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_metadata_proto_rawDescData []byte
)

func file_kubling_provider_v1_metadata_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_metadata_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_metadata_proto_rawDesc), len(file_kubling_provider_v1_metadata_proto_rawDesc)))
	})
	return file_kubling_provider_v1_metadata_proto_rawDescData
}

var file_kubling_provider_v1_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_kubling_provider_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_kubling_provider_v1_metadata_proto_goTypes = []any{
	(TableKind)(0),                    // 0: kubling.provider.v1.TableKind
	(KeyKind)(0),                      // 1: kubling.provider.v1.KeyKind
	(ColumnSearchability)(0),          // 2: kubling.provider.v1.ColumnSearchability
	(SyntheticCardinality)(0),         // 3: kubling.provider.v1.SyntheticCardinality
	(ParentColumnScope)(0),            // 4: kubling.provider.v1.ParentColumnScope
	(SyntheticMutationStrategy)(0),    // 5: kubling.provider.v1.SyntheticMutationStrategy
	(*SchemaMetadata)(nil),            // 6: kubling.provider.v1.SchemaMetadata
	(*NamespaceMetadata)(nil),         // 7: kubling.provider.v1.NamespaceMetadata
	(*TableMetadata)(nil),             // 8: kubling.provider.v1.TableMetadata
	(*ColumnMetadata)(nil),            // 9: kubling.provider.v1.ColumnMetadata
	(*SyntheticTableMetadata)(nil),    // 10: kubling.provider.v1.SyntheticTableMetadata
	(*TableReference)(nil),            // 11: kubling.provider.v1.TableReference
	(*SyntheticColumnBinding)(nil),    // 12: kubling.provider.v1.SyntheticColumnBinding
	(*DocumentColumnBinding)(nil),     // 13: kubling.provider.v1.DocumentColumnBinding
	(*ParentColumnBinding)(nil),       // 14: kubling.provider.v1.ParentColumnBinding
	(*OrdinalityColumnBinding)(nil),   // 15: kubling.provider.v1.OrdinalityColumnBinding
	(*SyntheticMutationMetadata)(nil), // 16: kubling.provider.v1.SyntheticMutationMetadata
	(*KeyMetadata)(nil),               // 17: kubling.provider.v1.KeyMetadata
	nil,                               // 18: kubling.provider.v1.SchemaMetadata.PropertiesEntry
	nil,                               // 19: kubling.provider.v1.NamespaceMetadata.PropertiesEntry
	nil,                               // 20: kubling.provider.v1.TableMetadata.PropertiesEntry
	nil,                               // 21: kubling.provider.v1.ColumnMetadata.PropertiesEntry
	nil,                               // 22: kubling.provider.v1.KeyMetadata.PropertiesEntry
	(v1.ValueType)(0),                 // 23: kubling.v1.ValueType
}
var file_kubling_provider_v1_metadata_proto_depIdxs = []int32{
	8,  // 0: kubling.provider.v1.SchemaMetadata.tables:type_name -> kubling.provider.v1.TableMetadata
	18, // 1: kubling.provider.v1.SchemaMetadata.properties:type_name -> kubling.provider.v1.SchemaMetadata.PropertiesEntry
	7,  // 2: kubling.provider.v1.SchemaMetadata.namespaces:type_name -> kubling.provider.v1.NamespaceMetadata
	19, // 3: kubling.provider.v1.NamespaceMetadata.properties:type_name -> kubling.provider.v1.NamespaceMetadata.PropertiesEntry
	0,  // 4: kubling.provider.v1.TableMetadata.kind:type_name -> kubling.provider.v1.TableKind
	9,  // 5: kubling.provider.v1.TableMetadata.columns:type_name -> kubling.provider.v1.ColumnMetadata
	17, // 6: kubling.provider.v1.TableMetadata.keys:type_name -> kubling.provider.v1.KeyMetadata
	20, // 7: kubling.provider.v1.TableMetadata.properties:type_name -> kubling.provider.v1.TableMetadata.PropertiesEntry
	10, // 8: kubling.provider.v1.TableMetadata.synthetic:type_name -> kubling.provider.v1.SyntheticTableMetadata
	23, // 9: kubling.provider.v1.ColumnMetadata.type:type_name -> kubling.v1.ValueType
	2,  // 10: kubling.provider.v1.ColumnMetadata.searchability:type_name -> kubling.provider.v1.ColumnSearchability
	21, // 11: kubling.provider.v1.ColumnMetadata.properties:type_name -> kubling.provider.v1.ColumnMetadata.PropertiesEntry
	11, // 12: kubling.provider.v1.SyntheticTableMetadata.parent:type_name -> kubling.provider.v1.TableReference
	3,  // 13: kubling.provider.v1.SyntheticTableMetadata.cardinality:type_name -> kubling.provider.v1.SyntheticCardinality
	12, // 14: kubling.provider.v1.SyntheticTableMetadata.column_bindings:type_name -> kubling.provider.v1.SyntheticColumnBinding
	16, // 15: kubling.provider.v1.SyntheticTableMetadata.mutations:type_name -> kubling.provider.v1.SyntheticMutationMetadata
	13, // 16: kubling.provider.v1.SyntheticColumnBinding.document:type_name -> kubling.provider.v1.DocumentColumnBinding
	14, // 17: kubling.provider.v1.SyntheticColumnBinding.parent:type_name -> kubling.provider.v1.ParentColumnBinding
	15, // 18: kubling.provider.v1.SyntheticColumnBinding.ordinality:type_name -> kubling.provider.v1.OrdinalityColumnBinding
	4,  // 19: kubling.provider.v1.ParentColumnBinding.scope:type_name -> kubling.provider.v1.ParentColumnScope
	5,  // 20: kubling.provider.v1.SyntheticMutationMetadata.strategy:type_name -> kubling.provider.v1.SyntheticMutationStrategy
	1,  // 21: kubling.provider.v1.KeyMetadata.kind:type_name -> kubling.provider.v1.KeyKind
	22, // 22: kubling.provider.v1.KeyMetadata.properties:type_name -> kubling.provider.v1.KeyMetadata.PropertiesEntry
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_metadata_proto_init() }
func file_kubling_provider_v1_metadata_proto_init() {
	if File_kubling_provider_v1_metadata_proto != nil {
		return
	}
	file_kubling_provider_v1_metadata_proto_msgTypes[2].OneofWrappers = []any{}
	file_kubling_provider_v1_metadata_proto_msgTypes[3].OneofWrappers = []any{}
	file_kubling_provider_v1_metadata_proto_msgTypes[6].OneofWrappers = []any{
		(*SyntheticColumnBinding_Document)(nil),
		(*SyntheticColumnBinding_Parent)(nil),
		(*SyntheticColumnBinding_Ordinality)(nil),
	}
	file_kubling_provider_v1_metadata_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_metadata_proto_rawDesc), len(file_kubling_provider_v1_metadata_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_metadata_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_metadata_proto_depIdxs,
		EnumInfos:         file_kubling_provider_v1_metadata_proto_enumTypes,
		MessageInfos:      file_kubling_provider_v1_metadata_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_metadata_proto = out.File
	file_kubling_provider_v1_metadata_proto_goTypes = nil
	file_kubling_provider_v1_metadata_proto_depIdxs = nil
}
