// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/mutation.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Inserts one or more tuples into a logical entity.
type InsertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Logical entity into which the tuples are inserted.
	Entity *EntityReference `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// Tuples to insert.
	//
	// TupleBatch.fields identifies the target logical fields and their order.
	// Every tuple must contain exactly one value for each declared field.
	Rows *TupleBatch `protobuf:"bytes,3,opt,name=rows,proto3" json:"rows,omitempty"`
	// Logical fields whose generated values should be returned.
	//
	// When empty, no generated values are requested.
	ReturningFields []string `protobuf:"bytes,4,rep,name=returning_fields,json=returningFields,proto3" json:"returning_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *InsertRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *InsertRequest) GetEntity() *EntityReference {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *InsertRequest) GetRows() *TupleBatch {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *InsertRequest) GetReturningFields() []string {
	if x != nil {
		return x.ReturningFields
	}
	return nil
}

// Result of an insert operation.
type InsertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tuples inserted.
	//
	// When absent, the provider could not determine the affected row count.
	AffectedRows *uint64 `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3,oneof" json:"affected_rows,omitempty"`
	// Values generated by the data source.
	//
	// When present, fields must follow the order requested in returning_fields.
	// Each tuple corresponds to the inserted tuple at the same position.
	GeneratedValues *TupleBatch `protobuf:"bytes,2,opt,name=generated_values,json=generatedValues,proto3" json:"generated_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResponse) GetAffectedRows() uint64 {
	if x != nil && x.AffectedRows != nil {
		return *x.AffectedRows
	}
	return 0
}

func (x *InsertResponse) GetGeneratedValues() *TupleBatch {
	if x != nil {
		return x.GeneratedValues
	}
	return nil
}

// Updates tuples in a logical entity.
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Logical entity to update.
	Entity *EntityReference `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// Values to assign to logical fields.
	Assignments []*Assignment `protobuf:"bytes,3,rep,name=assignments,proto3" json:"assignments,omitempty"`
	// Optional filter selecting the tuples to update.
	//
	// When absent, every tuple in the entity is selected.
	// Kubling must only include expressions supported by the provider.
	Filter        *Expression `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *UpdateRequest) GetEntity() *EntityReference {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *UpdateRequest) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *UpdateRequest) GetFilter() *Expression {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Assignment performed by an update operation.
type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical field to update.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Expression whose result is assigned to the field.
	//
	// Kubling must only send expressions supported by the provider.
	Value         *Expression `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Assignment) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

// Result of an update operation.
type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tuples updated.
	//
	// When absent, the provider could not determine the affected row count.
	AffectedRows  *uint64 `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3,oneof" json:"affected_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetAffectedRows() uint64 {
	if x != nil && x.AffectedRows != nil {
		return *x.AffectedRows
	}
	return 0
}

// Deletes tuples from a logical entity.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Logical entity from which tuples are deleted.
	Entity *EntityReference `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// Optional filter selecting the tuples to delete.
	//
	// When absent, every tuple in the entity is selected.
	// Kubling must only include expressions supported by the provider.
	Filter        *Expression `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *DeleteRequest) GetEntity() *EntityReference {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *DeleteRequest) GetFilter() *Expression {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Result of a delete operation.
type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tuples deleted.
	//
	// When absent, the provider could not determine the affected row count.
	AffectedRows  *uint64 `protobuf:"varint,1,opt,name=affected_rows,json=affectedRows,proto3,oneof" json:"affected_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_mutation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_mutation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetAffectedRows() uint64 {
	if x != nil && x.AffectedRows != nil {
		return *x.AffectedRows
	}
	return 0
}

var File_kubling_provider_v1_mutation_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_mutation_proto_rawDesc = "" +
	"\n" +
	"\"kubling/provider/v1/mutation.proto\x12\x13kubling.provider.v1\x1a$kubling/provider/v1/expression.proto\x1a\x1fkubling/provider/v1/query.proto\x1a\x1fkubling/provider/v1/tuple.proto\"\xd2\x01\n" +
	"\rInsertRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12<\n" +
	"\x06entity\x18\x02 \x01(\v2$.kubling.provider.v1.EntityReferenceR\x06entity\x123\n" +
	"\x04rows\x18\x03 \x01(\v2\x1f.kubling.provider.v1.TupleBatchR\x04rows\x12)\n" +
	"\x10returning_fields\x18\x04 \x03(\tR\x0freturningFields\"\x98\x01\n" +
	"\x0eInsertResponse\x12(\n" +
	"\raffected_rows\x18\x01 \x01(\x04H\x00R\faffectedRows\x88\x01\x01\x12J\n" +
	"\x10generated_values\x18\x02 \x01(\v2\x1f.kubling.provider.v1.TupleBatchR\x0fgeneratedValuesB\x10\n" +
	"\x0e_affected_rows\"\xee\x01\n" +
	"\rUpdateRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12<\n" +
	"\x06entity\x18\x02 \x01(\v2$.kubling.provider.v1.EntityReferenceR\x06entity\x12A\n" +
	"\vassignments\x18\x03 \x03(\v2\x1f.kubling.provider.v1.AssignmentR\vassignments\x127\n" +
	"\x06filter\x18\x04 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x06filter\"Y\n" +
	"\n" +
	"Assignment\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x05value\"L\n" +
	"\x0eUpdateResponse\x12(\n" +
	"\raffected_rows\x18\x01 \x01(\x04H\x00R\faffectedRows\x88\x01\x01B\x10\n" +
	"\x0e_affected_rows\"\xab\x01\n" +
	"\rDeleteRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12<\n" +
	"\x06entity\x18\x02 \x01(\v2$.kubling.provider.v1.EntityReferenceR\x06entity\x127\n" +
	"\x06filter\x18\x03 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x06filter\"L\n" +
	"\x0eDeleteResponse\x12(\n" +
	"\raffected_rows\x18\x01 \x01(\x04H\x00R\faffectedRows\x88\x01\x01B\x10\n" +
	"\x0e_affected_rowsB\x82\x01\n" +
	"\x19com.kubling.provider.grpcB\rMutationProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_mutation_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_mutation_proto_rawDescData []byte
)

func file_kubling_provider_v1_mutation_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_mutation_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_mutation_proto_rawDesc), len(file_kubling_provider_v1_mutation_proto_rawDesc)))
	})
	return file_kubling_provider_v1_mutation_proto_rawDescData
}

var file_kubling_provider_v1_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kubling_provider_v1_mutation_proto_goTypes = []any{
	(*InsertRequest)(nil),   // 0: kubling.provider.v1.InsertRequest
	(*InsertResponse)(nil),  // 1: kubling.provider.v1.InsertResponse
	(*UpdateRequest)(nil),   // 2: kubling.provider.v1.UpdateRequest
	(*Assignment)(nil),      // 3: kubling.provider.v1.Assignment
	(*UpdateResponse)(nil),  // 4: kubling.provider.v1.UpdateResponse
	(*DeleteRequest)(nil),   // 5: kubling.provider.v1.DeleteRequest
	(*DeleteResponse)(nil),  // 6: kubling.provider.v1.DeleteResponse
	(*EntityReference)(nil), // 7: kubling.provider.v1.EntityReference
	(*TupleBatch)(nil),      // 8: kubling.provider.v1.TupleBatch
	(*Expression)(nil),      // 9: kubling.provider.v1.Expression
}
var file_kubling_provider_v1_mutation_proto_depIdxs = []int32{
	7, // 0: kubling.provider.v1.InsertRequest.entity:type_name -> kubling.provider.v1.EntityReference
	8, // 1: kubling.provider.v1.InsertRequest.rows:type_name -> kubling.provider.v1.TupleBatch
	8, // 2: kubling.provider.v1.InsertResponse.generated_values:type_name -> kubling.provider.v1.TupleBatch
	7, // 3: kubling.provider.v1.UpdateRequest.entity:type_name -> kubling.provider.v1.EntityReference
	3, // 4: kubling.provider.v1.UpdateRequest.assignments:type_name -> kubling.provider.v1.Assignment
	9, // 5: kubling.provider.v1.UpdateRequest.filter:type_name -> kubling.provider.v1.Expression
	9, // 6: kubling.provider.v1.Assignment.value:type_name -> kubling.provider.v1.Expression
	7, // 7: kubling.provider.v1.DeleteRequest.entity:type_name -> kubling.provider.v1.EntityReference
	9, // 8: kubling.provider.v1.DeleteRequest.filter:type_name -> kubling.provider.v1.Expression
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_mutation_proto_init() }
func file_kubling_provider_v1_mutation_proto_init() {
	if File_kubling_provider_v1_mutation_proto != nil {
		return
	}
	file_kubling_provider_v1_expression_proto_init()
	file_kubling_provider_v1_query_proto_init()
	file_kubling_provider_v1_tuple_proto_init()
	file_kubling_provider_v1_mutation_proto_msgTypes[1].OneofWrappers = []any{}
	file_kubling_provider_v1_mutation_proto_msgTypes[4].OneofWrappers = []any{}
	file_kubling_provider_v1_mutation_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_mutation_proto_rawDesc), len(file_kubling_provider_v1_mutation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_mutation_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_mutation_proto_depIdxs,
		MessageInfos:      file_kubling_provider_v1_mutation_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_mutation_proto = out.File
	file_kubling_provider_v1_mutation_proto_goTypes = nil
	file_kubling_provider_v1_mutation_proto_depIdxs = nil
}
