// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/query.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction used for ordering query results.
type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASCENDING   SortDirection = 1
	SortDirection_SORT_DIRECTION_DESCENDING  SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASCENDING",
		2: "SORT_DIRECTION_DESCENDING",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASCENDING":   1,
		"SORT_DIRECTION_DESCENDING":  2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_query_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_query_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{0}
}

// Position of null values in an ordered result.
type NullOrdering int32

const (
	NullOrdering_NULL_ORDERING_UNSPECIFIED NullOrdering = 0
	NullOrdering_NULL_ORDERING_FIRST       NullOrdering = 1
	NullOrdering_NULL_ORDERING_LAST        NullOrdering = 2
)

// Enum value maps for NullOrdering.
var (
	NullOrdering_name = map[int32]string{
		0: "NULL_ORDERING_UNSPECIFIED",
		1: "NULL_ORDERING_FIRST",
		2: "NULL_ORDERING_LAST",
	}
	NullOrdering_value = map[string]int32{
		"NULL_ORDERING_UNSPECIFIED": 0,
		"NULL_ORDERING_FIRST":       1,
		"NULL_ORDERING_LAST":        2,
	}
)

func (x NullOrdering) Enum() *NullOrdering {
	p := new(NullOrdering)
	*p = x
	return p
}

func (x NullOrdering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullOrdering) Descriptor() protoreflect.EnumDescriptor {
	return file_kubling_provider_v1_query_proto_enumTypes[1].Descriptor()
}

func (NullOrdering) Type() protoreflect.EnumType {
	return &file_kubling_provider_v1_query_proto_enumTypes[1]
}

func (x NullOrdering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullOrdering.Descriptor instead.
func (NullOrdering) EnumDescriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{1}
}

// Query executed against a logical provider connection.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque identifier returned by OpenConnection.
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Logical entity to query.
	//
	// The provider is responsible for mapping this name to its native
	// representation in the data source.
	Entity *EntityReference `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// Ordered expressions to return.
	//
	// The order determines the order of fields and values in the resulting
	// TupleBatch.
	Projections []*Projection `protobuf:"bytes,3,rep,name=projections,proto3" json:"projections,omitempty"`
	// Optional filter expression.
	//
	// Kubling must only include expressions supported by the provider.
	Filter *Expression `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Ordered sorting rules.
	OrderBy []*OrderBy `protobuf:"bytes,5,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Maximum number of tuples to return.
	//
	// When absent, no limit is requested.
	Limit *uint64 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Number of tuples to skip before returning results.
	//
	// When absent, no offset is requested.
	Offset *uint64 `protobuf:"varint,7,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Preferred maximum number of tuples per streamed batch.
	//
	// This is a hint. When absent, the provider chooses an appropriate
	// batch size.
	BatchSize     *uint32 `protobuf:"varint,8,opt,name=batch_size,json=batchSize,proto3,oneof" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_kubling_provider_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *QueryRequest) GetEntity() *EntityReference {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *QueryRequest) GetProjections() []*Projection {
	if x != nil {
		return x.Projections
	}
	return nil
}

func (x *QueryRequest) GetFilter() *Expression {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryRequest) GetOrderBy() []*OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *QueryRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *QueryRequest) GetBatchSize() uint32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

// Logical entity exposed through the Kubling model.
type EntityReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical entity name known by Kubling.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque logical provider namespace containing the entity.
	//
	// Kubling sends the value advertised by the provider unchanged.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityReference) Reset() {
	*x = EntityReference{}
	mi := &file_kubling_provider_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityReference) ProtoMessage() {}

func (x *EntityReference) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityReference.ProtoReflect.Descriptor instead.
func (*EntityReference) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *EntityReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Expression returned as part of the query result.
type Projection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression to evaluate and return.
	Expression *Expression `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Logical name expected in the corresponding TupleBatch field.
	OutputName    string `protobuf:"bytes,2,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projection) Reset() {
	*x = Projection{}
	mi := &file_kubling_provider_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projection) ProtoMessage() {}

func (x *Projection) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projection.ProtoReflect.Descriptor instead.
func (*Projection) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *Projection) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *Projection) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

// Ordering rule applied by the provider.
type OrderBy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression used to order the result.
	Expression *Expression `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Sort direction.
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=kubling.provider.v1.SortDirection" json:"direction,omitempty"`
	// Required ordering of null values.
	NullOrdering  NullOrdering `protobuf:"varint,3,opt,name=null_ordering,json=nullOrdering,proto3,enum=kubling.provider.v1.NullOrdering" json:"null_ordering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_kubling_provider_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBy) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *OrderBy) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

func (x *OrderBy) GetNullOrdering() NullOrdering {
	if x != nil {
		return x.NullOrdering
	}
	return NullOrdering_NULL_ORDERING_UNSPECIFIED
}

// Streamed query result.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch of tuples produced by the provider.
	Batch         *TupleBatch `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_kubling_provider_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetBatch() *TupleBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

var File_kubling_provider_v1_query_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1fkubling/provider/v1/query.proto\x12\x13kubling.provider.v1\x1a$kubling/provider/v1/expression.proto\x1a\x1fkubling/provider/v1/tuple.proto\"\xa6\x03\n" +
	"\fQueryRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12<\n" +
	"\x06entity\x18\x02 \x01(\v2$.kubling.provider.v1.EntityReferenceR\x06entity\x12A\n" +
	"\vprojections\x18\x03 \x03(\v2\x1f.kubling.provider.v1.ProjectionR\vprojections\x127\n" +
	"\x06filter\x18\x04 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\x06filter\x127\n" +
	"\border_by\x18\x05 \x03(\v2\x1c.kubling.provider.v1.OrderByR\aorderBy\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x04H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\a \x01(\x04H\x01R\x06offset\x88\x01\x01\x12\"\n" +
	"\n" +
	"batch_size\x18\b \x01(\rH\x02R\tbatchSize\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\r\n" +
	"\v_batch_size\"C\n" +
	"\x0fEntityReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"n\n" +
	"\n" +
	"Projection\x12?\n" +
	"\n" +
	"expression\x18\x01 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\n" +
	"expression\x12\x1f\n" +
	"\voutput_name\x18\x02 \x01(\tR\n" +
	"outputName\"\xd4\x01\n" +
	"\aOrderBy\x12?\n" +
	"\n" +
	"expression\x18\x01 \x01(\v2\x1f.kubling.provider.v1.ExpressionR\n" +
	"expression\x12@\n" +
	"\tdirection\x18\x02 \x01(\x0e2\".kubling.provider.v1.SortDirectionR\tdirection\x12F\n" +
	"\rnull_ordering\x18\x03 \x01(\x0e2!.kubling.provider.v1.NullOrderingR\fnullOrdering\"F\n" +
	"\rQueryResponse\x125\n" +
	"\x05batch\x18\x01 \x01(\v2\x1f.kubling.provider.v1.TupleBatchR\x05batch*l\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SORT_DIRECTION_ASCENDING\x10\x01\x12\x1d\n" +
	"\x19SORT_DIRECTION_DESCENDING\x10\x02*^\n" +
	"\fNullOrdering\x12\x1d\n" +
	"\x19NULL_ORDERING_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NULL_ORDERING_FIRST\x10\x01\x12\x16\n" +
	"\x12NULL_ORDERING_LAST\x10\x02B\x7f\n" +
	"\x19com.kubling.provider.grpcB\n" +
	"QueryProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_query_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_query_proto_rawDescData []byte
)

func file_kubling_provider_v1_query_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_query_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_query_proto_rawDesc), len(file_kubling_provider_v1_query_proto_rawDesc)))
	})
	return file_kubling_provider_v1_query_proto_rawDescData
}

var file_kubling_provider_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kubling_provider_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kubling_provider_v1_query_proto_goTypes = []any{
	(SortDirection)(0),      // 0: kubling.provider.v1.SortDirection
	(NullOrdering)(0),       // 1: kubling.provider.v1.NullOrdering
	(*QueryRequest)(nil),    // 2: kubling.provider.v1.QueryRequest
	(*EntityReference)(nil), // 3: kubling.provider.v1.EntityReference
	(*Projection)(nil),      // 4: kubling.provider.v1.Projection
	(*OrderBy)(nil),         // 5: kubling.provider.v1.OrderBy
	(*QueryResponse)(nil),   // 6: kubling.provider.v1.QueryResponse
	(*Expression)(nil),      // 7: kubling.provider.v1.Expression
	(*TupleBatch)(nil),      // 8: kubling.provider.v1.TupleBatch
}
var file_kubling_provider_v1_query_proto_depIdxs = []int32{
	3, // 0: kubling.provider.v1.QueryRequest.entity:type_name -> kubling.provider.v1.EntityReference
	4, // 1: kubling.provider.v1.QueryRequest.projections:type_name -> kubling.provider.v1.Projection
	7, // 2: kubling.provider.v1.QueryRequest.filter:type_name -> kubling.provider.v1.Expression
	5, // 3: kubling.provider.v1.QueryRequest.order_by:type_name -> kubling.provider.v1.OrderBy
	7, // 4: kubling.provider.v1.Projection.expression:type_name -> kubling.provider.v1.Expression
	7, // 5: kubling.provider.v1.OrderBy.expression:type_name -> kubling.provider.v1.Expression
	0, // 6: kubling.provider.v1.OrderBy.direction:type_name -> kubling.provider.v1.SortDirection
	1, // 7: kubling.provider.v1.OrderBy.null_ordering:type_name -> kubling.provider.v1.NullOrdering
	8, // 8: kubling.provider.v1.QueryResponse.batch:type_name -> kubling.provider.v1.TupleBatch
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_query_proto_init() }
func file_kubling_provider_v1_query_proto_init() {
	if File_kubling_provider_v1_query_proto != nil {
		return
	}
	file_kubling_provider_v1_expression_proto_init()
	file_kubling_provider_v1_tuple_proto_init()
	file_kubling_provider_v1_query_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_query_proto_rawDesc), len(file_kubling_provider_v1_query_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_query_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_query_proto_depIdxs,
		EnumInfos:         file_kubling_provider_v1_query_proto_enumTypes,
		MessageInfos:      file_kubling_provider_v1_query_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_query_proto = out.File
	file_kubling_provider_v1_query_proto_goTypes = nil
	file_kubling_provider_v1_query_proto_depIdxs = nil
}
