// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/semantic.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests the optional source-local semantic fragment exposed by this
// provider server. Semantic fragment retrieval is connection-agnostic.
type GetSemanticFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSemanticFragmentRequest) Reset() {
	*x = GetSemanticFragmentRequest{}
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSemanticFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemanticFragmentRequest) ProtoMessage() {}

func (x *GetSemanticFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemanticFragmentRequest.ProtoReflect.Descriptor instead.
func (*GetSemanticFragmentRequest) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_semantic_proto_rawDescGZIP(), []int{0}
}

// Optional source-local semantic artifact exposed by the provider.
//
// An absent fragment means that the provider does not offer semantic metadata.
type GetSemanticFragmentResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Fragment      *SemanticFragmentArtifact `protobuf:"bytes,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSemanticFragmentResponse) Reset() {
	*x = GetSemanticFragmentResponse{}
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSemanticFragmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemanticFragmentResponse) ProtoMessage() {}

func (x *GetSemanticFragmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemanticFragmentResponse.ProtoReflect.Descriptor instead.
func (*GetSemanticFragmentResponse) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_semantic_proto_rawDescGZIP(), []int{1}
}

func (x *GetSemanticFragmentResponse) GetFragment() *SemanticFragmentArtifact {
	if x != nil {
		return x.Fragment
	}
	return nil
}

// Self-contained, versioned kubling-semantic document.
type SemanticFragmentArtifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact UTF-8 document bytes.
	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// Canonical media type. Initially application/yaml or application/json.
	MediaType string `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Exact provider-defined document version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// SHA-256 digest of the exact document bytes in sha256:<lowercase-hex> form.
	Digest        string `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticFragmentArtifact) Reset() {
	*x = SemanticFragmentArtifact{}
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticFragmentArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticFragmentArtifact) ProtoMessage() {}

func (x *SemanticFragmentArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_semantic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticFragmentArtifact.ProtoReflect.Descriptor instead.
func (*SemanticFragmentArtifact) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_semantic_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticFragmentArtifact) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SemanticFragmentArtifact) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *SemanticFragmentArtifact) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SemanticFragmentArtifact) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

var File_kubling_provider_v1_semantic_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_semantic_proto_rawDesc = "" +
	"\n" +
	"\"kubling/provider/v1/semantic.proto\x12\x13kubling.provider.v1\"\x1c\n" +
	"\x1aGetSemanticFragmentRequest\"h\n" +
	"\x1bGetSemanticFragmentResponse\x12I\n" +
	"\bfragment\x18\x01 \x01(\v2-.kubling.provider.v1.SemanticFragmentArtifactR\bfragment\"\x87\x01\n" +
	"\x18SemanticFragmentArtifact\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\fR\bdocument\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digestB\x82\x01\n" +
	"\x19com.kubling.provider.grpcB\rSemanticProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_semantic_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_semantic_proto_rawDescData []byte
)

func file_kubling_provider_v1_semantic_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_semantic_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_semantic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_semantic_proto_rawDesc), len(file_kubling_provider_v1_semantic_proto_rawDesc)))
	})
	return file_kubling_provider_v1_semantic_proto_rawDescData
}

var file_kubling_provider_v1_semantic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubling_provider_v1_semantic_proto_goTypes = []any{
	(*GetSemanticFragmentRequest)(nil),  // 0: kubling.provider.v1.GetSemanticFragmentRequest
	(*GetSemanticFragmentResponse)(nil), // 1: kubling.provider.v1.GetSemanticFragmentResponse
	(*SemanticFragmentArtifact)(nil),    // 2: kubling.provider.v1.SemanticFragmentArtifact
}
var file_kubling_provider_v1_semantic_proto_depIdxs = []int32{
	2, // 0: kubling.provider.v1.GetSemanticFragmentResponse.fragment:type_name -> kubling.provider.v1.SemanticFragmentArtifact
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_semantic_proto_init() }
func file_kubling_provider_v1_semantic_proto_init() {
	if File_kubling_provider_v1_semantic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_semantic_proto_rawDesc), len(file_kubling_provider_v1_semantic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_semantic_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_semantic_proto_depIdxs,
		MessageInfos:      file_kubling_provider_v1_semantic_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_semantic_proto = out.File
	file_kubling_provider_v1_semantic_proto_goTypes = nil
	file_kubling_provider_v1_semantic_proto_depIdxs = nil
}
