// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubling/provider/v1/tuple.proto

package providerv1

import (
	v1 "github.com/kubling-community/kubling-grpc/sdk-go/kubling/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes a field returned by the provider.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field name exposed to Kubling.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Logical Kubling type of the field.
	//
	// This metadata also determines the logical type of null values.
	Type          v1.ValueType `protobuf:"varint,2,opt,name=type,proto3,enum=kubling.v1.ValueType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_tuple_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() v1.ValueType {
	if x != nil {
		return x.Type
	}
	return v1.ValueType(0)
}

// Ordered tuple of values.
//
// The position of each value corresponds to the field at the same position
// in TupleBatch.fields.
type Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*v1.Value            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_tuple_proto_rawDescGZIP(), []int{1}
}

func (x *Tuple) GetValues() []*v1.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Batch of tuples returned by the provider.
type TupleBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered field metadata shared by every tuple in this batch.
	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// Tuples contained in the batch.
	//
	// Every tuple must contain exactly one value for each declared field.
	Tuples        []*Tuple `protobuf:"bytes,2,rep,name=tuples,proto3" json:"tuples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleBatch) Reset() {
	*x = TupleBatch{}
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleBatch) ProtoMessage() {}

func (x *TupleBatch) ProtoReflect() protoreflect.Message {
	mi := &file_kubling_provider_v1_tuple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleBatch.ProtoReflect.Descriptor instead.
func (*TupleBatch) Descriptor() ([]byte, []int) {
	return file_kubling_provider_v1_tuple_proto_rawDescGZIP(), []int{2}
}

func (x *TupleBatch) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TupleBatch) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

var File_kubling_provider_v1_tuple_proto protoreflect.FileDescriptor

const file_kubling_provider_v1_tuple_proto_rawDesc = "" +
	"\n" +
	"\x1fkubling/provider/v1/tuple.proto\x12\x13kubling.provider.v1\x1a\x16kubling/v1/value.proto\"F\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.kubling.v1.ValueTypeR\x04type\"2\n" +
	"\x05Tuple\x12)\n" +
	"\x06values\x18\x01 \x03(\v2\x11.kubling.v1.ValueR\x06values\"t\n" +
	"\n" +
	"TupleBatch\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.kubling.provider.v1.FieldR\x06fields\x122\n" +
	"\x06tuples\x18\x02 \x03(\v2\x1a.kubling.provider.v1.TupleR\x06tuplesB\x7f\n" +
	"\x19com.kubling.provider.grpcB\n" +
	"TupleProtoP\x01ZTgithub.com/kubling-community/kubling-providers/sdk-go/kubling/provider/v1;providerv1b\x06proto3"

var (
	file_kubling_provider_v1_tuple_proto_rawDescOnce sync.Once
	file_kubling_provider_v1_tuple_proto_rawDescData []byte
)

func file_kubling_provider_v1_tuple_proto_rawDescGZIP() []byte {
	file_kubling_provider_v1_tuple_proto_rawDescOnce.Do(func() {
		file_kubling_provider_v1_tuple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_tuple_proto_rawDesc), len(file_kubling_provider_v1_tuple_proto_rawDesc)))
	})
	return file_kubling_provider_v1_tuple_proto_rawDescData
}

var file_kubling_provider_v1_tuple_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubling_provider_v1_tuple_proto_goTypes = []any{
	(*Field)(nil),      // 0: kubling.provider.v1.Field
	(*Tuple)(nil),      // 1: kubling.provider.v1.Tuple
	(*TupleBatch)(nil), // 2: kubling.provider.v1.TupleBatch
	(v1.ValueType)(0),  // 3: kubling.v1.ValueType
	(*v1.Value)(nil),   // 4: kubling.v1.Value
}
var file_kubling_provider_v1_tuple_proto_depIdxs = []int32{
	3, // 0: kubling.provider.v1.Field.type:type_name -> kubling.v1.ValueType
	4, // 1: kubling.provider.v1.Tuple.values:type_name -> kubling.v1.Value
	0, // 2: kubling.provider.v1.TupleBatch.fields:type_name -> kubling.provider.v1.Field
	1, // 3: kubling.provider.v1.TupleBatch.tuples:type_name -> kubling.provider.v1.Tuple
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kubling_provider_v1_tuple_proto_init() }
func file_kubling_provider_v1_tuple_proto_init() {
	if File_kubling_provider_v1_tuple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubling_provider_v1_tuple_proto_rawDesc), len(file_kubling_provider_v1_tuple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubling_provider_v1_tuple_proto_goTypes,
		DependencyIndexes: file_kubling_provider_v1_tuple_proto_depIdxs,
		MessageInfos:      file_kubling_provider_v1_tuple_proto_msgTypes,
	}.Build()
	File_kubling_provider_v1_tuple_proto = out.File
	file_kubling_provider_v1_tuple_proto_goTypes = nil
	file_kubling_provider_v1_tuple_proto_depIdxs = nil
}
