name: In-memory Provider

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'providers/inmemory/v*'
    paths:
      - 'providers/inmemory/**'
      - 'sdk-go/**'
      - '.github/workflows/_go-module.yml'
      - '.github/workflows/provider-inmemory.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'providers/inmemory/**'
      - 'sdk-go/**'
      - '.github/workflows/_go-module.yml'
      - '.github/workflows/provider-inmemory.yml'

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/_go-module.yml
    with:
      module_name: In-memory provider
      module_directory: providers/inmemory
